import { describe, it, expect } from 'vitest';
import {
  generateRegoPolicy,
  getRegoPath,
  GENERATED_POLICIES_DIR,
  REGO_FILENAME,
  REGO_PACKAGE,
} from './rego-generator.js';
import type { ArchitectureDefinition } from './definition-schema.js';

describe('rego-generator', () => {
  const minimalDefinition: ArchitectureDefinition = {
    schema_version: '0.1.0',
    template: 'custom',
    layers: {},
    rules: [],
  };

  const layeredDefinition: ArchitectureDefinition = {
    schema_version: '0.1.0',
    template: 'layered',
    layers: {
      presentation: {
        patterns: ['src/ui/**/*.ts', 'src/components/**/*.ts'],
        depends_on: ['business'],
      },
      business: {
        patterns: ['src/services/**/*.ts', 'src/domain/**/*.ts'],
        depends_on: ['data'],
      },
      data: {
        patterns: ['src/repositories/**/*.ts', 'src/db/**/*.ts'],
        depends_on: [],
      },
    },
    rules: [
      {
        name: 'no-ui-to-data',
        from: 'presentation',
        to: 'data',
        severity: 'error',
        allowed: false,
        message: 'UI layer must not access data layer directly',
      },
    ],
    options: {
      detect_orphans: true,
      detect_circular: true,
      default_severity: 'error',
      exclude_patterns: ['**/*.test.ts'],
    },
  };

  describe('getRegoPath', () => {
    const toFwd = (p: string): string => p.replace(/\\/g, '/');

    it('returns correct path', () => {
      const path = getRegoPath('/workspace');
      expect(toFwd(path)).toBe(`/workspace/${GENERATED_POLICIES_DIR}/${REGO_FILENAME}`);
    });
  });

  describe('generateRegoPolicy', () => {
    it('generates valid Rego header', () => {
      const rego = generateRegoPolicy(minimalDefinition);
      expect(rego).toContain('# Auto-generated by anvil - do not edit manually');
      expect(rego).toContain('# hash:');
      expect(rego).toContain(`package ${REGO_PACKAGE}`);
      expect(rego).toContain('import rego.v1');
    });

    it('includes definition hash for regeneration check', () => {
      const rego = generateRegoPolicy(minimalDefinition);
      const hashMatch = rego.match(/# hash: ([a-f0-9]+)/);
      expect(hashMatch).not.toBeNull();
      expect(hashMatch![1]).toHaveLength(16);
    });

    it('generates layer definitions', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('layers := ["presentation","business","data"]');
    });

    it('generates allowed dependencies map', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('allowed_deps := {');
      expect(rego).toContain('"presentation":["business"]');
      expect(rego).toContain('"business":["data"]');
      expect(rego).toContain('"data":[]');
    });

    it('includes layer_can_depend helper', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('layer_can_depend(source, target)');
    });

    it('generates layer boundary violation rule', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('violation contains result if {');
      expect(rego).toContain('not layer_can_depend(v.from_layer, v.to_layer)');
      expect(rego).toContain('"rule": "layer-boundary"');
    });

    it('layer boundary rule filters on is_new flag', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      // Find the layer-boundary rule block
      const lines = rego.split('\n');
      const startIdx = lines.findIndex((l) => l.includes('# Detect layer boundary violations'));
      const endIdx = lines.findIndex((l, idx) => idx > startIdx && l === '}');
      const ruleBlock = lines.slice(startIdx, endIdx + 1).join('\n');

      // Verify the rule checks is_new flag
      expect(ruleBlock).toContain('v.is_new');
    });

    it('generates circular dependency rule when enabled', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('detect_circular := true');
      expect(rego).toContain('v.is_circular');
      expect(rego).toContain('"rule": "no-circular"');
    });

    it('circular dependency rule filters on is_new flag', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      // Find the no-circular rule block
      const lines = rego.split('\n');
      const startIdx = lines.findIndex((l) => l.includes('# Detect circular dependencies'));
      const endIdx = lines.findIndex((l, idx) => idx > startIdx && l === '}');
      const ruleBlock = lines.slice(startIdx, endIdx + 1).join('\n');

      // Verify the rule checks is_new flag
      expect(ruleBlock).toContain('v.is_new');
    });

    it('generates new violation detection rule', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('v.is_new');
      expect(rego).toContain('"rule": "new-violation"');
    });

    it('generates explicit rules from definition', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('# Rule: no-ui-to-data');
      expect(rego).toContain('v.from_layer == "presentation"');
      expect(rego).toContain('v.to_layer == "data"');
      expect(rego).toContain('UI layer must not access data layer directly');
    });

    it('explicit rules filter on is_new flag', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      // Find the explicit rule block
      const lines = rego.split('\n');
      const startIdx = lines.findIndex((l) => l.includes('# Rule: no-ui-to-data'));
      const endIdx = lines.findIndex((l, idx) => idx > startIdx && l === '}');
      const ruleBlock = lines.slice(startIdx, endIdx + 1).join('\n');

      // Verify the rule checks is_new flag
      expect(ruleBlock).toContain('v.is_new');
    });

    it('generates summary helper', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('summary := {');
      expect(rego).toContain('"total_violations": count(violation)');
    });

    it('generates deny and warn rules', () => {
      const rego = generateRegoPolicy(layeredDefinition);
      expect(rego).toContain('deny contains msg if {');
      expect(rego).toContain('v.severity == "error"');
      expect(rego).toContain('warn contains msg if {');
      expect(rego).toContain('v.severity == "warn"');
    });

    it('uses default options when not specified', () => {
      const rego = generateRegoPolicy(minimalDefinition);
      expect(rego).toContain('detect_circular := true');
      expect(rego).toContain('default_severity := "error"');
    });

    it('produces deterministic hash for same definition', () => {
      const rego1 = generateRegoPolicy(layeredDefinition);
      const rego2 = generateRegoPolicy(layeredDefinition);
      const hash1 = rego1.match(/# hash: ([a-f0-9]+)/)?.[1];
      const hash2 = rego2.match(/# hash: ([a-f0-9]+)/)?.[1];
      expect(hash1).toBe(hash2);
    });

    it('produces different hash for different definitions', () => {
      const rego1 = generateRegoPolicy(minimalDefinition);
      const rego2 = generateRegoPolicy(layeredDefinition);
      const hash1 = rego1.match(/# hash: ([a-f0-9]+)/)?.[1];
      const hash2 = rego2.match(/# hash: ([a-f0-9]+)/)?.[1];
      expect(hash1).not.toBe(hash2);
    });
  });
});
