import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import type { ArchitectureDefinition } from './definition-schema.js';
import { createDebugger } from '../utils/debug.js';

const debug = createDebugger('compiler');

export const GENERATED_POLICIES_DIR = '.anvil/policies/.generated';
export const REGO_FILENAME = 'architecture.rego';
export const REGO_PACKAGE = 'anvil.policies.architecture';

/**
 * Get the path to the generated Rego file
 */
export function getRegoPath(workspaceRoot: string): string {
  return join(workspaceRoot, GENERATED_POLICIES_DIR, REGO_FILENAME);
}

/**
 * Check if generated Rego file exists
 */
export function regoExists(workspaceRoot: string): boolean {
  return existsSync(getRegoPath(workspaceRoot));
}

/**
 * Check if Rego needs regeneration based on definition hash
 */
export async function needsRegoRegeneration(
  workspaceRoot: string,
  definition: ArchitectureDefinition
): Promise<boolean> {
  const regoPath = getRegoPath(workspaceRoot);
  if (!existsSync(regoPath)) {
    return true;
  }
  const existingContent = await readFile(regoPath, 'utf-8');
  const hashMatch = existingContent.match(/# hash: ([a-f0-9]+)/);
  if (!hashMatch) {
    return true;
  }
  const currentHash = computeDefinitionHash(definition);
  return hashMatch[1] !== currentHash;
}

function computeDefinitionHash(definition: ArchitectureDefinition): string {
  const content = JSON.stringify(definition);
  return createHash('sha256').update(content).digest('hex').slice(0, 16);
}

/**
 * Write generated Rego policy file
 */
export async function writeRegoPolicy(
  workspaceRoot: string,
  definition: ArchitectureDefinition
): Promise<string> {
  const regoPath = getRegoPath(workspaceRoot);
  debug('writing Rego policy', regoPath);
  const regoDir = dirname(regoPath);
  await mkdir(regoDir, { recursive: true });
  const content = generateRegoPolicy(definition);
  await writeFile(regoPath, content, 'utf-8');
  return regoPath;
}

/**
 * Generate Rego policy content from architecture definition
 */
export function generateRegoPolicy(definition: ArchitectureDefinition): string {
  const hash = computeDefinitionHash(definition);
  const lines: string[] = [];

  // Header
  lines.push('# Auto-generated by anvil - do not edit manually');
  lines.push(`# hash: ${hash}`);
  lines.push('# Generated from: .anvil/architecture.yaml');
  lines.push('#');
  lines.push('# This policy enforces architecture boundaries defined in architecture.yaml.');
  lines.push('# It uses the architecture context provided by ArchitectureCheck.');
  lines.push('');
  lines.push(`package ${REGO_PACKAGE}`);
  lines.push('');
  lines.push('import rego.v1');
  lines.push('');

  // Generate layer definitions as data
  lines.push('# Layer definitions from architecture.yaml');
  lines.push(`layers := ${JSON.stringify(Object.keys(definition.layers))}`);
  lines.push('');

  // Generate allowed dependencies map
  const allowedDeps: Record<string, string[]> = {};
  for (const [layerName, layerDef] of Object.entries(definition.layers)) {
    allowedDeps[layerName] = layerDef.depends_on;
  }
  lines.push('# Allowed dependencies per layer');
  lines.push(`allowed_deps := ${JSON.stringify(allowedDeps)}`);
  lines.push('');

  // Generate options
  const options = definition.options ?? {
    detect_circular: true,
    default_severity: 'error',
  };
  lines.push('# Options');
  lines.push(`detect_circular := ${options.detect_circular ?? true}`);
  lines.push(`default_severity := "${options.default_severity ?? 'error'}"`);
  lines.push('');

  // Helper function to check if a layer can depend on another
  lines.push('# Check if source layer is allowed to depend on target layer');
  lines.push('layer_can_depend(source, target) if {');
  lines.push('  source == target  # Same layer is always allowed');
  lines.push('}');
  lines.push('');
  lines.push('layer_can_depend(source, target) if {');
  lines.push('  allowed := allowed_deps[source]');
  lines.push('  target in allowed');
  lines.push('}');
  lines.push('');

  // Violation rule for layer boundary violations
  lines.push('# Detect layer boundary violations from architecture context');
  lines.push('violation contains result if {');
  lines.push('  some v in input.architecture.violations');
  lines.push('  v.from_layer != null');
  lines.push('  v.to_layer != null');
  lines.push('  not layer_can_depend(v.from_layer, v.to_layer)');
  lines.push('  v.is_new');
  lines.push('  result := {');
  lines.push('    "rule": "layer-boundary",');
  lines.push('    "severity": v.severity,');
  lines.push(
    '    "message": sprintf("%s (%s) cannot depend on %s (%s)", [v.from, v.from_layer, v.to, v.to_layer]),'
  );
  lines.push('    "path": v.from,');
  lines.push('    "category": "architecture",');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Violation rule for circular dependencies
  lines.push('# Detect circular dependencies');
  lines.push('violation contains result if {');
  lines.push('  detect_circular');
  lines.push('  some v in input.architecture.violations');
  lines.push('  v.is_circular');
  lines.push('  v.is_new');
  lines.push('  result := {');
  lines.push('    "rule": "no-circular",');
  lines.push('    "severity": default_severity,');
  lines.push('    "message": sprintf("Circular dependency: %s -> %s", [v.from, v.to]),');
  lines.push('    "path": v.from,');
  lines.push('    "category": "architecture",');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Violation rule for new violations (not in baseline)
  lines.push('# Flag new violations (not in baseline)');
  lines.push('violation contains result if {');
  lines.push('  some v in input.architecture.violations');
  lines.push('  v.is_new');
  lines.push('  result := {');
  lines.push('    "rule": "new-violation",');
  lines.push('    "severity": "warning",');
  lines.push(
    '    "message": sprintf("New architecture violation: %s -> %s (%s)", [v.from, v.to, v.rule]),'
  );
  lines.push('    "path": v.from,');
  lines.push('    "category": "architecture",');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Generate explicit rules from definition
  if (definition.rules.length > 0) {
    lines.push('# Explicit rules from architecture.yaml');
    for (const rule of definition.rules) {
      if (!rule.allowed) {
        // This is a forbidden dependency rule
        const fromLayer = definition.layers[rule.from];
        const toLayer = definition.layers[rule.to];
        if (fromLayer && toLayer) {
          const ruleName = sanitiseRuleName(rule.name);
          lines.push(`# Rule: ${rule.name}`);
          lines.push(`violation contains result if {`);
          lines.push(`  some v in input.architecture.violations`);
          lines.push(`  v.from_layer == "${rule.from}"`);
          lines.push(`  v.to_layer == "${rule.to}"`);
          lines.push(`  v.is_new`);
          lines.push(`  result := {`);
          lines.push(`    "rule": "${ruleName}",`);
          lines.push(`    "severity": "${rule.severity}",`);
          lines.push(
            `    "message": "${escapeString(rule.message || `${rule.from} must not depend on ${rule.to}`)}",`
          );
          lines.push(`    "path": v.from,`);
          lines.push(`    "category": "architecture",`);
          lines.push(`  }`);
          lines.push(`}`);
          lines.push('');
        }
      }
    }
  }

  // Summary helper for external use
  lines.push('# Summary of architecture health');
  lines.push('summary := {');
  lines.push('  "total_violations": count(violation),');
  lines.push('  "layer_violations": count([v | some v in violation; v.rule == "layer-boundary"]),');
  lines.push('  "circular_violations": count([v | some v in violation; v.rule == "no-circular"]),');
  lines.push('  "new_violations": count([v | some v in violation; v.rule == "new-violation"]),');
  lines.push('}');
  lines.push('');

  // Deny rule for blocking on errors
  lines.push('# Deny if any error-level violations exist');
  lines.push('deny contains msg if {');
  lines.push('  some v in violation');
  lines.push('  v.severity == "error"');
  lines.push('  msg := v.message');
  lines.push('}');
  lines.push('');

  // Warn rule for warning-level violations
  lines.push('# Warn for warning-level violations');
  lines.push('warn contains msg if {');
  lines.push('  some v in violation');
  lines.push('  v.severity == "warn"');
  lines.push('  msg := v.message');
  lines.push('}');
  lines.push('');
  lines.push('warn contains msg if {');
  lines.push('  some v in violation');
  lines.push('  v.severity == "warning"');
  lines.push('  msg := v.message');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Sanitise rule name for use in Rego
 */
function sanitiseRuleName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/**
 * Escape string for Rego string literal
 */
function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}
