version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore(dev)'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
    labels:
      - 'github-actions'
