config:
  keyvault:vaultName: kv-iac-anvil
  azure-dns:resourceGroupName: rg-prd-ap-public-web
secretsprovider: azurekeyvault://kv-iac-anvil.vault.azure.net/keys/pulumi-secrets-key
encryptedkey: TWNEcjdyOHV4RDBtUmVja2F2QjZzX2dpdHE1WlNtTTJaRDJ2bm1LWU1lUVRod1VjMkZwVHZ5Wmxpd21TMHNQbG5pNmpFOXlFOXEtT0RDTExPV05tTk9DSElIRTBwUE5VRm9ESmo4b0xsYS1UWURoZ0tMdFFNN0wwNEhPTTZ5WjJKVkhWNm5aYmVkRWN0c2xTZ0luM0k0dEhWbFI3Rmc0MGJzdWFOVmIwVnNMemtGSmVneVFBTWtwaHRUZU1kWnd2dnM4cW1uMU0wbUZ6UUR0bHFmcE5pemZ0b3Y1YXV1RW9KUVp5cVNDMl8ySTZ3Vmk2VlprR3pmTFRPLXpGUzRQd0VrQVUwS2xfdFdXck5iQk1QTEYwcnJMVk96RG1RMWppaS1fWlZQSUJ5Z1ZtVHZtVW4xM0daUW1XMktibmxMcTc1Mjc2OFZ2aHB0WmVhT1FSVDhtN0R3
