config:
  keyvault:vaultName: kv-iac-anvil
  azure-dns:resourceGroupName: rg-prd-ap-public-web
secretsprovider: azurekeyvault://kv-iac-anvil.vault.azure.net/keys/pulumi-secrets-key
encryptedkey: R2ZUR1NUVFVzbjdnOTdGMkR6VmRpdjh5S3haWEhzZ0M3SXlVOXd5eUk3cFN1Wk9oOGFNVVhJcU5TVzdDWWdteDRvemZseGd2ck4weEZ6NFR5a1ZERUc4YkMyVGlTNC1GYVNSZ1E4RGlkbFRKOGlvT2NwaklIUWdYRUh4OG9UdXlaYktoczVobTZOODRkSldvRlJ3blF5d1pqS0VqR3p6Nmdmd09LN3dxZHQ2RHZwWFVRWTlyWEQ2UE0zNVdRMnBmeGFXX3ozNDVrWXBVTkFFUVFxVjlwamdiWDdqRjAyQllVTGFlSW9BR2xzZDVSRmUxNk92VVlsOTh1OHcwZWQydEdjZlkyTnF5d0NES0RwelFMcnJDb3ZrTEhaSE9BYzFORnU2N28xYmpjV1o0MkdrQ2FIdVZfMVF3Z2NaUGtXUWU0ZG5qMlViQlZoNVZqN1gyQ09VWUV3
