import { Hono } from 'hono';
import { z } from 'zod';
import { zValidator } from '@hono/zod-validator';
import { randomBytes } from 'node:crypto';
import { getClient } from '../db/client.js';
import {
  findUserByEmail,
  findUserById,
  insertDeviceCode,
  insertDummyDeviceCode,
  findPendingDeviceCodeWithUserId,
  confirmDeviceCode,
  incrementDeviceCodeAttempts,
  pollDeviceCode,
  deviceCodeExistsByPollToken,
  consumeDeviceCode,
} from '../db/queries.js';
import { createDebugger } from '../lib/debug.js';
import {
  MAX_USER_CODE_RETRIES,
  generateUserCode,
  isUserCodeCollision,
} from '../lib/device-code.js';
import { mintSession } from '../lib/session.js';
import { hashToken } from '../lib/token.js';
import { requireAuth } from '../middleware/require-auth.js';

const debug = createDebugger('auth-device');

const POLL_INTERVAL_S = 5;

// Per-code brute-force ceiling for /device/confirm. Once a user_code row has
// recorded this many failed email matches, further confirms are rejected
// regardless of the submitted email — the legitimate user must request a new
// code. Mirrors the otp_codes.attempts pattern at a higher threshold because
// the email pairing makes guessing harder than a 6-digit OTP. See issue #922.
const MAX_ATTEMPTS = 5;

function generatePollToken(): string {
  return randomBytes(32).toString('hex');
}

const startSchema = z.object({
  email: z.string().email().max(254),
});

const confirmSchema = z.object({
  // Accepts 14-char codes generated by all current endpoints (randomBytes(4))
  // plus legacy 22-char codes still live in device_codes from pre-PR-920
  // /admin/approve calls (randomBytes(8)) until their 48h expiry lapses.
  //
  // No `email` field — issue #1779 critical: the previous shape trusted a
  // caller-supplied email and let any caller mint tokens for any active
  // user. The bound user is now derived from the `Authorization: Bearer`
  // licence via `requireAuth` middleware below.
  userCode: z.string().min(1).max(30),
});

const pollSchema = z.object({
  pollToken: z.string().min(1).max(200),
});

const authDevice = new Hono();

/**
 * POST /auth/device/start
 *
 * Initiates the device code authentication flow.
 * Anti-enumeration: always returns the same response shape regardless of
 * whether the email belongs to an active user.
 */
authDevice.post('/start', zValidator('json', startSchema), async (c) => {
  const { email } = c.req.valid('json');
  debug('POST /auth/device/start', { hasEmail: Boolean(email) });

  const normalised = email.toLowerCase().trim();
  const sql = getClient();

  const user = await findUserByEmail(sql, normalised);
  const isValid = user && user.status === 'active';

  const pollToken = generatePollToken();
  const pollTokenHash = hashToken(pollToken);
  const expiresAt = new Date(Date.now() + 900_000); // 15 minutes

  let userCode = '';
  for (let attempt = 0; attempt < MAX_USER_CODE_RETRIES; attempt++) {
    userCode = generateUserCode();
    try {
      if (isValid) {
        await insertDeviceCode(sql, user.id, userCode, pollTokenHash, expiresAt);
        debug('device code created', { userCode });
      } else {
        // F-C-003: insert a dummy row so /confirm has identical DB-query timing
        // for non-existent users. The null user_id ensures the JOIN in /confirm
        // never matches, and the row expires normally via cron cleanup.
        await insertDummyDeviceCode(sql, userCode, pollTokenHash, expiresAt);
        debug('anti-enumeration dummy device code created');
      }
      break;
    } catch (err: unknown) {
      if (!isUserCodeCollision(err) || attempt === MAX_USER_CODE_RETRIES - 1) throw err;
      debug('user_code collision, retrying', { attempt });
    }
  }

  const verificationUrl = process.env.ACTIVATE_URL ?? 'https://eddacraft.ai/auth/activate';

  return c.json({
    userCode,
    verificationUrl,
    pollToken,
    expiresIn: 900,
    interval: POLL_INTERVAL_S,
  });
});

/**
 * POST /auth/device/confirm
 *
 * Confirms a device code from the browser activation page. Requires the
 * caller to be authenticated as the user the device code was issued for —
 * the bound user is read from the `Authorization: Bearer` licence and
 * matched against the device_codes row's `user_id` (never against any
 * body-supplied email).
 *
 * Anti-enumeration: returns identical error for all failure modes
 * downstream of auth, including the row-not-found, attempts-locked, and
 * user-mismatch cases.
 *
 * Closes the issue #1779 critical bypass where the previous shape trusted
 * a caller-supplied email — any caller who knew an active user's email
 * could complete the flow as that user.
 */
authDevice.post('/confirm', requireAuth(), zValidator('json', confirmSchema), async (c) => {
  const { userCode } = c.req.valid('json');
  const authed = c.get('authed');
  debug('POST /auth/device/confirm', { authedSub: authed.sub });

  const normalisedCode = userCode.toUpperCase().trim();
  const sql = getClient();

  const result = await findPendingDeviceCodeWithUserId(sql, normalisedCode);

  if (!result) {
    // Anti-enumeration: response identical to the user-mismatch case
    // below. Server log only.
    debug('confirm rejected: no matching pending device code');
    return c.json({ error: 'Invalid or expired code' }, 400);
  }
  if (result.attempts >= MAX_ATTEMPTS) {
    // Row exists but has been locked out by prior failed attempts.
    // Reject even if the authed user is correct — the legitimate user
    // re-issues a new code. Logged for operator metrics.
    debug('confirm rejected: device code locked', {
      id: result.id,
      attempts: result.attempts,
    });
    return c.json({ error: 'Invalid or expired code' }, 400);
  }
  if (result.user_id === null || result.user_id !== authed.sub) {
    // Either an anti-enumeration dummy row (user_id IS NULL) or a code
    // bound to a different user. Increment the per-code attempt counter
    // (DB-bounded by `WHERE attempts < ${max}` so concurrent bursts
    // still cap at MAX_ATTEMPTS) and return the anti-enum response.
    const attempts = await incrementDeviceCodeAttempts(sql, result.id, MAX_ATTEMPTS);
    debug('confirm rejected: user mismatch for code', {
      id: result.id,
      attempts,
      lockedOut: attempts === null || attempts >= MAX_ATTEMPTS,
    });
    return c.json({ error: 'Invalid or expired code' }, 400);
  }

  await confirmDeviceCode(sql, result.id);

  return c.json({ confirmed: true });
});

/**
 * POST /auth/device/poll
 *
 * Polls for the status of a device code flow. The CLI calls this repeatedly
 * until the user confirms the code on the web or the code expires.
 *
 * Rate limiting: per-token cooldown enforced via `last_polled_at` column.
 * Returns 429 with `slow_down` error if polled within the 5-second interval.
 */
authDevice.post('/poll', zValidator('json', pollSchema), async (c) => {
  debug('POST /auth/device/poll');
  const { pollToken } = c.req.valid('json');
  const sql = getClient();
  const pollTokenHash = hashToken(pollToken);

  // F-C-006: atomic per-token rate limiting — single UPDATE-with-WHERE
  // eliminates TOCTOU race between reading and stamping last_polled_at
  const deviceCode = await pollDeviceCode(sql, pollTokenHash, POLL_INTERVAL_S);

  if (!deviceCode) {
    // Either the token doesn't exist or the cooldown hasn't elapsed.
    // Distinguish "not found" from "rate limited" with a read-only check.
    const exists = await deviceCodeExistsByPollToken(sql, pollTokenHash);

    if (exists) {
      debug('poll rate limited (too frequent)');
      return c.json({ error: 'slow_down', retryAfter: POLL_INTERVAL_S }, 429);
    }

    // Anti-enumeration is handled upstream: /start inserts dummy rows for
    // inactive users (F-C-003), so both valid and invalid users get identical
    // polling behaviour. A token with no row was never issued — return expired.
    debug('device code not found (no matching row — treating as expired)');
    return c.json({ status: 'expired' });
  }

  // Check expiry BEFORE any further side-effects (session minting)
  const expiresAt = new Date(deviceCode.expires_at);
  if (expiresAt.getTime() < Date.now()) {
    debug('device code expired');
    return c.json({ status: 'expired' });
  }

  if (!deviceCode.confirmed_at) {
    debug('device code pending');
    return c.json({ status: 'pending' });
  }

  // Confirmed — atomically consume the device code so concurrent polls
  // cannot both mint sessions (DELETE ... RETURNING ensures single-use)
  const consumed = await consumeDeviceCode(sql, pollTokenHash);

  if (!consumed) {
    debug('device code already consumed by concurrent request');
    return c.json({ status: 'expired' });
  }

  debug('device code confirmed, issuing licence');
  const userId = consumed.user_id;

  const user = await findUserById(sql, userId);

  if (!user || user.status !== 'active') {
    debug('user not found or not active for confirmed device code');
    return c.json({ status: 'expired' });
  }

  // Mint the licence + refresh token. Scope resolution keeps a graded-scope
  // grant (e.g. `preview`) through the device-code activation flow; defaults
  // to `['beta']` for users with no prior access_tokens row.
  const session = await mintSession(sql, {
    user,
    identity: { provider: 'email', id: null },
  });

  debug('device code consumed, licence issued');

  return c.json({ status: 'confirmed', ...session });
});

export { authDevice };
