//! Detection of machine-generated source files.
//!
//! Anti-pattern rules describe defects a human author can act on. A file emitted
//! by a code generator — `TanStack` Router's `routeTree.gen.ts`, protobuf/gRPC
//! stubs, GraphQL codegen output, ORM clients — is not hand-authored, is usually
//! overwritten on the next `generate` run, and routinely ships blanket
//! `eslint-disable` / `@ts-nocheck` headers *by construction*. Scanning it for
//! anti-patterns produces findings the user cannot action (CIB-199).
//!
//! Detection uses two orthogonal signals, deliberately **not** keyed on the
//! suppression markers the `guardrail-suppression` family exists to catch
//! (`/* eslint-disable */`, `// @ts-nocheck`). Using those as the exemption
//! would let any author silence the whole anti-pattern gate for a file by
//! writing the very thing AP-001 detects. Instead:
//!
//! 1. **Path convention** — a `*.gen.*` / `*.generated.*` filename infix, or a
//!    `generated` / `.generated` / `__generated__` path segment. Covers `TanStack`
//!    Router, GraphQL codegen, and similar.
//! 2. **Generator banner** — a high-precision attribution phrase in the leading
//!    lines (the GitHub-Linguist `linguist-generated` convention): `@generated`,
//!    `Code generated by`, `automatically generated`, `auto-generated`. Covers
//!    protobuf/Go-style stubs that use a plain path but stamp a banner.
//!
//! Known limitation: both signals are spoofable (rename to `*.gen.ts`, or paste
//! a banner). This is the same trade-off GitHub Linguist accepts. The durable
//! answer to pre-existing-violation noise is finding-baselining, not content
//! trust — see the ADR-002 reconciliation tracked alongside CIB-199.

/// Number of leading lines scanned for a generator banner. Bounded so a
/// hand-written file cannot bury a "generated" comment deep in its body and go
/// unscanned.
const BANNER_SCAN_LINES: usize = 10;

/// High-precision, lowercase generator-attribution phrases. Matched
/// case-insensitively against the leading lines of a file. Kept deliberately
/// narrow: each phrase is one a hand author is very unlikely to write, so a
/// match is strong evidence the file is generated.
const BANNER_MARKERS: &[&str] = &[
    "@generated",
    "code generated by",
    "automatically generated",
    "auto-generated",
    "autogenerated",
];

/// True when `path` matches a machine-generated file naming convention.
#[must_use]
pub fn is_generated_path(path: &str) -> bool {
    let normalised = path.replace('\\', "/");

    // Path-segment conventions: `generated/`, `.generated/`, `__generated__/`.
    let has_generated_segment = normalised
        .split('/')
        .any(|seg| matches!(seg, "generated" | ".generated" | "__generated__"));
    if has_generated_segment {
        return true;
    }

    // Filename infix conventions: `foo.gen.ts`, `foo.generated.ts`.
    let file = normalised.rsplit('/').next().unwrap_or(normalised.as_str());
    file.contains(".gen.") || file.contains(".generated.")
}

/// True when the first [`BANNER_SCAN_LINES`] lines of `content` carry a
/// generator-attribution banner.
#[must_use]
pub fn has_generated_banner(content: &str) -> bool {
    content.lines().take(BANNER_SCAN_LINES).any(|line| {
        let lower = line.to_ascii_lowercase();
        BANNER_MARKERS.iter().any(|marker| lower.contains(marker))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gen_infix_filename_is_generated() {
        assert!(is_generated_path("src/routeTree.gen.ts"));
        assert!(is_generated_path("apps/staff-portal/src/routeTree.gen.ts"));
        assert!(is_generated_path("schema.generated.ts"));
    }

    #[test]
    fn generated_path_segment_is_generated() {
        assert!(is_generated_path("src/generated/graphql.ts"));
        assert!(is_generated_path("src/__generated__/types.ts"));
        assert!(is_generated_path("app/.generated/client.ts"));
        assert!(is_generated_path("a\\b\\generated\\c.ts")); // windows separators
    }

    #[test]
    fn hand_written_path_is_not_generated() {
        assert!(!is_generated_path("src/routes/index.ts"));
        assert!(!is_generated_path("src/generator.ts")); // substring, not a segment
        assert!(!is_generated_path("src/regenerate.ts"));
    }

    #[test]
    fn generator_banner_is_detected() {
        assert!(has_generated_banner(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\n"
        ));
        assert!(has_generated_banner(
            "/* @generated */\nexport const x = 1;\n"
        ));
        assert!(has_generated_banner(
            "// This file is automatically generated.\n"
        ));
        assert!(has_generated_banner("# Auto-generated. Do not edit.\n"));
    }

    #[test]
    fn banner_only_scanned_in_leading_lines() {
        let mut body = "export const a = 1;\n".repeat(20);
        body.push_str("// @generated\n"); // buried past the scan window
        assert!(!has_generated_banner(&body));
    }

    #[test]
    fn suppression_markers_alone_are_not_a_generated_signal() {
        // The exact shape that trips AP-001. It must NOT be treated as
        // generated by either signal, or any author could silence the gate by
        // writing it.
        let content = "/* eslint-disable */\n// @ts-nocheck\nexport const x: any = 1;\n";
        assert!(!has_generated_banner(content));
        assert!(!is_generated_path("src/handwritten.ts"));
    }
}
