import type { components } from '@/api/generated/openapi';

export const protectionOverviewFixture = {
  schema_version: 'anvil.dashboard.protection.v1',
  data_state: 'partial',
  source_message: 'Offline development snapshot; last-known local evidence remains available.',
  claim: null,
  assurance: {
    state: 'stale',
    reason: 'daemon-absent',
    generation: 12,
    last_full_scan: '2026-07-13T08:30:00Z',
    scanned_files: 486,
    total_files: 486,
  },
  save_time: { state: 'attached', active: true, failure_count: 0 },
  observed_at_unix: 1_773_563_400,
  latest_run: {
    id: 'run-083000',
    result: 'issues',
    label: 'Completed with issues',
    score: 72,
    warning_count: 2,
    duration_seconds: 18.4,
    started_at: '2026-07-13 08:30:00',
    new_warning_count: 1,
    changed_file_count: 1,
    checks: [],
  },
  recent_runs: [
    {
      id: 'run-083000',
      result: 'issues',
      label: 'Completed with issues',
      score: 72,
      warning_count: 2,
      duration_seconds: 18.4,
      started_at: '2026-07-13 08:30:00',
      new_warning_count: 1,
      changed_file_count: 1,
      checks: [],
    },
    {
      id: 'run-081500',
      result: 'clean',
      label: 'Clean',
      score: 100,
      warning_count: 0,
      duration_seconds: 16.2,
      started_at: '2026-07-13 08:15:00',
      new_warning_count: 0,
      changed_file_count: 0,
      checks: [],
    },
  ],
  next_attention: {
    title: 'Review typed-secret-rule',
    detail: 'src/typed.ts:18',
    evidence_id: 'evidence-typed-secret',
  },
  warnings_state: 'complete',
  warnings: [
    {
      id: 'warning-typed-secret',
      severity: 'high',
      rule: 'typed-secret-rule',
      category: 'Secrets',
      message: 'A secret-shaped value was detected.',
      file_path: 'src/typed.ts',
      line: 18,
      age_label: '2m ago',
      evidence_id: 'evidence-typed-secret',
      explanation: 'The typed API evidence identifies a secret-shaped value at this boundary.',
      matched_pattern: 'secret_[a-z]+',
      evidence_excerpt: [
        { number: 17, text: 'const mode = "safe";', highlighted: false },
        { number: 18, text: 'const token = "redacted";', highlighted: true },
      ],
    },
  ],
  affected_files_state: 'complete',
  affected_files: [
    {
      path: 'src/typed.ts',
      highest_severity: 'high',
      warning_count: 1,
      first_seen: '2m ago',
      last_seen: 'now',
      warning_id: 'warning-typed-secret',
    },
  ],
  gaps: [{ component: 'live-protection', reason: 'The local daemon is offline.' }],
} satisfies components['schemas']['ProtectionOverview'];
