use std::path::{Path, PathBuf};

use regex::Regex;
use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct LoadedPolicy {
    pub name: String,
    pub path: PathBuf,
    pub content: String,
    pub package: String,
    pub has_tests: bool,
    pub test_path: Option<PathBuf>,
    pub generated: bool,
    pub source_hash: Option<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum LoaderError {
    #[error("policy directory not found: {0}")]
    DirNotFound(PathBuf),
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("path traversal detected: {0}")]
    PathTraversal(PathBuf),
    #[error("no package declaration in {0}")]
    MissingPackage(PathBuf),
}

pub struct PolicyLoader {
    package_re: Regex,
    hash_re: Regex,
}

impl PolicyLoader {
    pub fn new() -> Self {
        Self {
            package_re: Regex::new(r"(?m)^\s*package\s+([\w.]+)").unwrap(),
            hash_re: Regex::new(r"(?m)^#\s*hash:\s*([a-f0-9]+)").unwrap(),
        }
    }

    pub fn load_policies(
        &self,
        workspace_root: &Path,
        policy_dir: Option<&str>,
    ) -> Result<Vec<LoadedPolicy>, LoaderError> {
        let dir = workspace_root.join(policy_dir.unwrap_or(".anvil/policies"));

        if !dir.exists() {
            return Ok(Vec::new());
        }

        let canonical_root = workspace_root
            .canonicalize()
            .map_err(|_| LoaderError::DirNotFound(workspace_root.to_path_buf()))?;
        let canonical_dir = dir
            .canonicalize()
            .map_err(|_| LoaderError::DirNotFound(dir.clone()))?;

        if !canonical_dir.starts_with(&canonical_root) {
            return Err(LoaderError::PathTraversal(dir));
        }

        let mut policies = Vec::new();

        for entry in walkdir::WalkDir::new(&canonical_dir)
            .into_iter()
            .filter_map(Result::ok)
            .filter(|e| e.file_type().is_file())
        {
            let path = entry.path();
            let name = path
                .file_name()
                .unwrap_or_default()
                .to_string_lossy()
                .to_string();

            if path.extension().is_none_or(|ext| ext != "rego") || name.ends_with("_test.rego") {
                continue;
            }

            match self.load_policy(path) {
                Ok(policy) => policies.push(policy),
                Err(LoaderError::Io(e)) if e.kind() == std::io::ErrorKind::PermissionDenied => {
                    return Err(LoaderError::Io(e));
                }
                Err(_) => {}
            }
        }

        policies.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(policies)
    }

    pub fn load_policy(&self, path: &Path) -> Result<LoadedPolicy, LoaderError> {
        let content = std::fs::read_to_string(path)?;

        let name = path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();

        let package = self
            .package_re
            .captures(&content)
            .and_then(|c| c.get(1))
            .map(|m| m.as_str().to_string())
            .ok_or_else(|| LoaderError::MissingPackage(path.to_path_buf()))?;

        let source_hash = self
            .hash_re
            .captures(&content)
            .and_then(|c| c.get(1))
            .map(|m| m.as_str().to_string());

        let generated = content.contains("# Auto-generated by Anvil")
            || path.components().any(|c| c.as_os_str() == ".generated");

        let test_name = format!("{name}_test.rego");
        let test_path = path.with_file_name(&test_name);
        let has_tests = test_path.exists();

        Ok(LoadedPolicy {
            name,
            path: path.to_path_buf(),
            content,
            package,
            has_tests,
            test_path: has_tests.then_some(test_path),
            generated,
            source_hash,
        })
    }

    pub fn find_test_files(&self, dir: &Path) -> Vec<PathBuf> {
        if !dir.exists() {
            return Vec::new();
        }

        walkdir::WalkDir::new(dir)
            .into_iter()
            .filter_map(Result::ok)
            .filter(|e| e.file_type().is_file())
            .filter(|e| {
                e.path()
                    .file_name()
                    .is_some_and(|n| n.to_string_lossy().ends_with("_test.rego"))
            })
            .map(|e| e.path().to_path_buf())
            .collect()
    }
}

impl Default for PolicyLoader {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn loads_rego_policies() {
        let tmp = tempfile::TempDir::new().unwrap();
        let policy_dir = tmp.path().join(".anvil/policies");
        fs::create_dir_all(&policy_dir).unwrap();

        fs::write(
            policy_dir.join("security.rego"),
            "package anvil.policies.security\n\nviolation[msg] { msg := \"test\" }\n",
        )
        .unwrap();
        fs::write(
            policy_dir.join("security_test.rego"),
            "package anvil.policies.security_test\n",
        )
        .unwrap();

        let loader = PolicyLoader::new();
        let policies = loader.load_policies(tmp.path(), None).unwrap();

        assert_eq!(policies.len(), 1);
        assert_eq!(policies[0].name, "security");
        assert_eq!(policies[0].package, "anvil.policies.security");
        assert!(policies[0].has_tests);
        assert!(!policies[0].generated);
    }

    #[test]
    fn detects_generated_policies() {
        let tmp = tempfile::TempDir::new().unwrap();
        let policy_dir = tmp.path().join(".anvil/policies");
        fs::create_dir_all(&policy_dir).unwrap();

        fs::write(
            policy_dir.join("auto.rego"),
            "# Auto-generated by Anvil\n# hash: abc123\npackage anvil.policies.auto\n",
        )
        .unwrap();

        let loader = PolicyLoader::new();
        let policies = loader.load_policies(tmp.path(), None).unwrap();

        assert_eq!(policies.len(), 1);
        assert!(policies[0].generated);
        assert_eq!(policies[0].source_hash.as_deref(), Some("abc123"));
    }

    #[test]
    fn returns_empty_for_missing_dir() {
        let tmp = tempfile::TempDir::new().unwrap();
        let loader = PolicyLoader::new();
        let policies = loader.load_policies(tmp.path(), None).unwrap();
        assert!(policies.is_empty());
    }

    #[test]
    fn returns_empty_for_nonexistent_policy_dir() {
        let tmp = tempfile::TempDir::new().unwrap();
        let loader = PolicyLoader::new();
        let result = loader.load_policies(tmp.path(), Some("nonexistent"));
        assert!(result.is_ok());
        assert!(result.unwrap().is_empty());
    }

    #[test]
    fn finds_test_files() {
        let tmp = tempfile::TempDir::new().unwrap();
        let policy_dir = tmp.path().join("policies");
        fs::create_dir_all(&policy_dir).unwrap();

        fs::write(policy_dir.join("a.rego"), "").unwrap();
        fs::write(policy_dir.join("a_test.rego"), "").unwrap();
        fs::write(policy_dir.join("b_test.rego"), "").unwrap();

        let loader = PolicyLoader::new();
        let tests = loader.find_test_files(&policy_dir);
        assert_eq!(tests.len(), 2);
    }
}
