import type { CommandRule } from './types.js';

export const DEFAULT_GIT_RULES: CommandRule[] = [
  {
    id: 'git-reset-hard',
    category: 'git',
    command: 'git',
    subcommand: 'reset',
    flags: { dangerous: ['--hard'] },
    action: 'block',
    severity: 'error',
    reason: 'git reset --hard permanently destroys uncommitted changes',
    suggestion:
      'Use "git stash" first to preserve your work, or "git reset --soft" for a safer alternative',
    references: [
      'https://git-scm.com/docs/git-reset',
      'https://ohshitgit.com/#accidental-commit-wrong-branch',
    ],
  },

  {
    id: 'git-reset-merge',
    category: 'git',
    command: 'git',
    subcommand: 'reset',
    flags: { dangerous: ['--merge'] },
    action: 'warn',
    severity: 'warning',
    reason: 'git reset --merge can lose uncommitted changes during conflict resolution',
    suggestion: 'Ensure all changes are committed or stashed before using --merge',
  },

  {
    id: 'git-checkout-discard',
    category: 'git',
    command: 'git',
    subcommand: 'checkout',
    flags: { dangerous: ['--'] },
    action: 'block',
    severity: 'error',
    reason: 'git checkout -- discards uncommitted changes permanently',
    suggestion: 'Use "git stash" to preserve changes, or "git diff" to review first',
    references: ['https://git-scm.com/docs/git-checkout'],
  },

  {
    id: 'git-checkout-all',
    category: 'git',
    command: 'git',
    subcommand: 'checkout',
    args: { pattern: /^\.$/ },
    action: 'warn',
    severity: 'warning',
    reason: 'git checkout . discards all uncommitted changes in the working tree',
    suggestion: 'Use "git stash" to preserve changes, or "git diff" to review first',
  },

  {
    id: 'git-restore-worktree',
    category: 'git',
    command: 'git',
    subcommand: 'restore',
    flags: { forbidden: ['--staged'] },
    action: 'block',
    severity: 'error',
    reason: 'git restore discards uncommitted changes permanently',
    suggestion: 'Use "git stash" first, or "git restore --staged" to only unstage',
  },

  {
    id: 'git-clean-force',
    category: 'git',
    command: 'git',
    subcommand: 'clean',
    flags: { dangerous: ['-f', '--force'], forbidden: ['-n', '--dry-run'] },
    action: 'warn',
    severity: 'warning',
    reason: 'git clean -f permanently removes untracked files',
    suggestion: 'Preview with "git clean -n" (dry-run) first',
  },

  {
    id: 'git-push-force',
    category: 'git',
    command: 'git',
    subcommand: 'push',
    flags: { dangerous: ['-f', '--force'], forbidden: ['--force-with-lease'] },
    action: 'block',
    severity: 'error',
    reason: 'git push --force rewrites remote history and can cause data loss for collaborators',
    suggestion:
      'Use "git push --force-with-lease" for safer force pushing, or coordinate with your team',
    references: [
      'https://git-scm.com/docs/git-push#Documentation/git-push.txt---force-with-leaseltrefnamegt',
    ],
  },

  {
    id: 'git-branch-force-delete',
    category: 'git',
    command: 'git',
    subcommand: 'branch',
    flags: { dangerous: ['-D'] },
    action: 'warn',
    severity: 'warning',
    reason: 'git branch -D force-deletes branches without merge verification',
    suggestion: 'Use "git branch -d" for safe deletion with merge checks',
  },

  {
    id: 'git-stash-drop',
    category: 'git',
    command: 'git',
    subcommand: 'stash',
    args: { pattern: /^drop$/, position: 0 },
    action: 'warn',
    severity: 'warning',
    reason: 'git stash drop permanently deletes stashed changes',
    suggestion: 'Review stashed changes with "git stash show -p" before dropping',
  },

  {
    id: 'git-stash-clear',
    category: 'git',
    command: 'git',
    subcommand: 'stash',
    args: { pattern: /^clear$/, position: 0 },
    action: 'warn',
    severity: 'warning',
    reason: 'git stash clear permanently deletes all stashed changes',
    suggestion: 'Review stashes with "git stash list" before clearing',
  },

  {
    id: 'git-rebase-abort',
    category: 'git',
    command: 'git',
    subcommand: 'rebase',
    flags: { dangerous: ['--abort'] },
    action: 'warn',
    severity: 'warning',
    reason: 'git rebase --abort discards rebase progress',
    suggestion: 'Ensure you want to discard all rebase progress before aborting',
  },

  {
    id: 'git-merge-abort',
    category: 'git',
    command: 'git',
    subcommand: 'merge',
    flags: { dangerous: ['--abort'] },
    action: 'warn',
    severity: 'warning',
    reason: 'git merge --abort discards merge progress',
    suggestion: 'Ensure you want to discard all merge progress before aborting',
  },

  {
    id: 'git-checkout-branch',
    category: 'git',
    command: 'git',
    subcommand: 'checkout',
    flags: { required: ['-b', '-B', '--orphan'] },
    action: 'allow',
    severity: 'info',
    reason: 'Branch creation is a safe operation',
  },

  {
    id: 'git-restore-staged',
    category: 'git',
    command: 'git',
    subcommand: 'restore',
    flags: { required: ['--staged'] },
    action: 'allow',
    severity: 'info',
    reason: 'Unstaging changes is a safe operation',
  },

  {
    id: 'git-push-force-with-lease',
    category: 'git',
    command: 'git',
    subcommand: 'push',
    flags: { required: ['--force-with-lease'] },
    action: 'allow',
    severity: 'info',
    reason: 'Force-with-lease is a safer alternative to --force',
  },

  {
    id: 'git-branch-safe-delete',
    category: 'git',
    command: 'git',
    subcommand: 'branch',
    flags: { required: ['-d'], forbidden: ['-D'] },
    action: 'allow',
    severity: 'info',
    reason: 'Safe branch deletion with merge verification',
  },

  {
    id: 'git-clean-dry-run',
    category: 'git',
    command: 'git',
    subcommand: 'clean',
    flags: { required: ['-n', '--dry-run'] },
    action: 'allow',
    severity: 'info',
    reason: 'Dry-run preview is safe',
  },
];
