/**
 * Policy Loader - Discover and load Rego policy files
 */

import { existsSync, readdirSync, statSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join, basename, extname, sep, resolve } from 'node:path';
import { createDebugger } from './utils/debug.js';

const debug = createDebugger('policy');

/**
 * Default policy directory relative to workspace root
 */
const DEFAULT_POLICY_DIR = '.anvil/policies';

/**
 * Represents a loaded policy file
 */
export interface LoadedPolicy {
  /** Policy name (filename without extension) */
  name: string;
  /** Full path to the .rego file */
  path: string;
  /** Policy source code */
  content: string;
  /** Rego package name extracted from source */
  package: string;
  /** Whether a corresponding _test.rego file exists */
  hasTests: boolean;
  /** Path to the test file (if hasTests is true) */
  testPath?: string;
  /** Whether this policy was auto-generated by Anvil */
  generated: boolean;
  /** Hash from generated policy header (if generated) */
  sourceHash?: string;
}

/**
 * Result of policy discovery
 */
export interface PolicyDiscoveryResult {
  /** Successfully loaded policies */
  policies: LoadedPolicy[];
  /** Files that failed to load with error messages */
  errors: Array<{ path: string; error: string }>;
  /** Policy directory path */
  directory: string;
}

/**
 * Configuration for policy loading
 */
export interface PolicyLoaderConfig {
  /** Custom policy directory (relative to workspace root) */
  policyDir?: string;
  /** Only load specific policies by name */
  enabledPolicies?: string[];
  /** Exclude specific policies by name */
  disabledPolicies?: string[];
}

/**
 * Discovers and loads Rego policy files
 */
export class PolicyLoader {
  /**
   * Load all policies from the policy directory
   */
  async loadPolicies(
    workspaceRoot: string,
    config: PolicyLoaderConfig = {}
  ): Promise<PolicyDiscoveryResult> {
    const policyDir = config.policyDir || DEFAULT_POLICY_DIR;
    const fullPolicyDir = join(workspaceRoot, policyDir);
    debug('loading policies from directory', fullPolicyDir);

    const result: PolicyDiscoveryResult = {
      policies: [],
      errors: [],
      directory: fullPolicyDir,
    };

    // Validate policy directory is within workspace root
    const resolvedRoot = resolve(workspaceRoot);
    const resolvedPolicy = resolve(fullPolicyDir);
    if (resolvedPolicy !== resolvedRoot && !resolvedPolicy.startsWith(resolvedRoot + sep)) {
      throw new Error(`Policy directory escapes workspace root: ${policyDir}`);
    }

    // Check if policy directory exists
    if (!existsSync(fullPolicyDir)) {
      debug('policy directory does not exist', fullPolicyDir);
      return result;
    }

    // Find all .rego files (excluding _test.rego)
    const regoFiles = this.findRegoFiles(fullPolicyDir);

    // Load each policy
    for (const filePath of regoFiles) {
      try {
        const policy = await this.loadPolicy(filePath);

        // Apply filters
        if (this.shouldIncludePolicy(policy.name, config)) {
          result.policies.push(policy);
        }
      } catch (error) {
        debug('failed to load policy', {
          path: filePath,
          error: error instanceof Error ? error.message : 'Unknown error',
        });
        result.errors.push({
          path: filePath,
          error: error instanceof Error ? error.message : 'Unknown error',
        });
      }
    }

    debug('policies loaded', { count: result.policies.length, errors: result.errors.length });
    return result;
  }

  async loadPolicy(filePath: string): Promise<LoadedPolicy> {
    const content = await readFile(filePath, 'utf-8');
    const name = this.extractPolicyName(filePath);
    const packageName = this.extractPackageName(content);
    const testPath = this.getTestFilePath(filePath);
    const hasTests = testPath !== undefined;
    const { generated, sourceHash } = this.detectGeneratedPolicy(filePath, content);

    return {
      name,
      path: filePath,
      content,
      package: packageName,
      hasTests,
      testPath,
      generated,
      sourceHash,
    };
  }

  /**
   * Find all .rego files in a directory (excluding test files)
   */
  private findRegoFiles(directory: string): string[] {
    const files: string[] = [];

    const entries = readdirSync(directory);
    for (const entry of entries) {
      const fullPath = join(directory, entry);
      const stat = statSync(fullPath);

      if (stat.isDirectory()) {
        // Recursively search subdirectories
        files.push(...this.findRegoFiles(fullPath));
      } else if (stat.isFile() && this.isRegoFile(entry) && !this.isTestFile(entry)) {
        files.push(fullPath);
      }
    }

    return files;
  }

  /**
   * Check if a filename is a .rego file
   */
  private isRegoFile(filename: string): boolean {
    return extname(filename).toLowerCase() === '.rego';
  }

  /**
   * Check if a filename is a test file
   */
  private isTestFile(filename: string): boolean {
    return filename.endsWith('_test.rego');
  }

  /**
   * Extract policy name from file path
   */
  private extractPolicyName(filePath: string): string {
    const filename = basename(filePath);
    return filename.replace(/\.rego$/, '');
  }

  /**
   * Extract package name from Rego source
   */
  private extractPackageName(content: string): string {
    // Match package declaration: package anvil.policies.coverage_min
    const match = content.match(/^\s*package\s+([\w.]+)/m);
    return match ? match[1] : 'unknown';
  }

  /**
   * Get the test file path if it exists
   */
  private getTestFilePath(policyPath: string): string | undefined {
    const testPath = policyPath.replace(/\.rego$/, '_test.rego');
    return existsSync(testPath) ? testPath : undefined;
  }

  private shouldIncludePolicy(policyName: string, config: PolicyLoaderConfig): boolean {
    if (config.disabledPolicies?.includes(policyName)) {
      return false;
    }

    if (config.enabledPolicies && config.enabledPolicies.length > 0) {
      return config.enabledPolicies.includes(policyName);
    }

    return true;
  }

  private detectGeneratedPolicy(
    filePath: string,
    content: string
  ): { generated: boolean; sourceHash?: string } {
    const generatedDirPattern = `${sep}.generated${sep}`;
    const isInGeneratedDir = filePath.includes(generatedDirPattern);
    // Accept both current lowercase brand and the pre-rebrand capitalised form.
    const hasGeneratedHeader =
      content.startsWith('# Auto-generated by anvil') ||
      content.startsWith('# Auto-generated by Anvil');
    const generated = isInGeneratedDir || hasGeneratedHeader;

    if (!generated) {
      return { generated: false };
    }

    const hashMatch = content.match(/^# hash: ([a-f0-9]+)/m);
    return {
      generated: true,
      sourceHash: hashMatch?.[1],
    };
  }

  /**
   * Get all test files for policies in a directory
   */
  findTestFiles(directory: string): string[] {
    const files: string[] = [];

    if (!existsSync(directory)) {
      return files;
    }

    const entries = readdirSync(directory);
    for (const entry of entries) {
      const fullPath = join(directory, entry);
      const stat = statSync(fullPath);

      if (stat.isDirectory()) {
        files.push(...this.findTestFiles(fullPath));
      } else if (stat.isFile() && this.isTestFile(entry)) {
        files.push(fullPath);
      }
    }

    return files;
  }
}
