import { writeFile, mkdir, readFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join, dirname } from 'path';
import { createHash } from 'crypto';
import type { ArchitectureDefinition } from './definition-schema.js';

export const DC_CONFIG_FILENAME = 'dependency-cruiser.js';
export const ANVIL_DIR = '.anvil';

export function getDCConfigPath(workspaceRoot: string): string {
  return join(workspaceRoot, ANVIL_DIR, DC_CONFIG_FILENAME);
}

export function dcConfigExists(workspaceRoot: string): boolean {
  return existsSync(getDCConfigPath(workspaceRoot));
}

export async function needsRegeneration(
  workspaceRoot: string,
  definition: ArchitectureDefinition
): Promise<boolean> {
  const configPath = getDCConfigPath(workspaceRoot);
  if (!existsSync(configPath)) {
    return true;
  }
  const existingContent = await readFile(configPath, 'utf-8');
  const hashMatch = existingContent.match(/\/\/ hash: ([a-f0-9]+)/);
  if (!hashMatch) {
    return true;
  }
  const currentHash = computeDefinitionHash(definition);
  return hashMatch[1] !== currentHash;
}

function computeDefinitionHash(definition: ArchitectureDefinition): string {
  const content = JSON.stringify(definition);
  return createHash('sha256').update(content).digest('hex').slice(0, 16);
}

export async function writeDCConfig(
  workspaceRoot: string,
  definition: ArchitectureDefinition
): Promise<string> {
  const configPath = getDCConfigPath(workspaceRoot);
  const configDir = dirname(configPath);
  if (!existsSync(configDir)) {
    await mkdir(configDir, { recursive: true });
  }
  const content = generateDCConfig(definition);
  await writeFile(configPath, content, 'utf-8');
  return configPath;
}

export function generateDCConfig(definition: ArchitectureDefinition): string {
  const hash = computeDefinitionHash(definition);
  const rules = generateRules(definition);
  const options = definition.options ?? {
    detect_orphans: true,
    detect_circular: true,
    default_severity: 'error',
    exclude_patterns: ['**/*.test.ts', '**/*.spec.ts', '**/__tests__/**', '**/node_modules/**'],
  };

  const config = {
    forbidden: rules,
    options: {
      doNotFollow: {
        path: 'node_modules',
      },
      exclude: {
        path: options.exclude_patterns,
      },
      tsPreCompilationDeps: true,
      enhancedResolveOptions: {
        exportsFields: ['exports'],
        conditionNames: ['import', 'require', 'node', 'default'],
      },
    },
  };

  return `// Auto-generated by Anvil - do not edit manually
// hash: ${hash}
// Generated from: .anvil/architecture.yaml

/** @type {import('dependency-cruiser').IConfiguration} */
module.exports = ${JSON.stringify(config, null, 2)};
`;
}

interface DCRule {
  name: string;
  severity: 'error' | 'warn' | 'info' | 'ignore';
  comment?: string;
  from: { path?: string; pathNot?: string | string[] };
  to: { path?: string; pathNot?: string | string[]; circular?: boolean };
}

function deduplicateRules(rules: DCRule[]): DCRule[] {
  const byName = new Map<string, { index: number; rule: DCRule }>();
  for (let i = 0; i < rules.length; i++) {
    const existing = byName.get(rules[i].name);
    byName.set(rules[i].name, {
      index: existing?.index ?? i,
      rule: rules[i],
    });
  }
  return Array.from(byName.values())
    .sort((a, b) => a.index - b.index)
    .map((entry) => entry.rule);
}

function generateRules(definition: ArchitectureDefinition): DCRule[] {
  const rules: DCRule[] = [];
  const options = definition.options ?? {
    detect_orphans: true,
    detect_circular: true,
    default_severity: 'error',
  };

  if (options.detect_circular) {
    rules.push({
      name: 'no-circular',
      severity: mapSeverity(options.default_severity),
      comment: 'Circular dependencies are not allowed',
      from: {},
      to: { circular: true },
    });
  }

  if (options.detect_orphans) {
    rules.push({
      name: 'no-orphans',
      severity: mapSeverity(options.default_severity ?? 'warn'),
      comment: 'Modules without dependents or dependencies',
      from: {
        pathNot: ['\\.d\\.ts$', '\\.test\\.(ts|js)$', '\\.spec\\.(ts|js)$', 'index\\.(ts|js)$'],
      },
      to: {},
    });
  }

  const layerNames = Object.keys(definition.layers);
  for (const [layerName, layerDef] of Object.entries(definition.layers)) {
    const allowedDeps = layerDef.depends_on;
    const disallowedLayers = layerNames.filter((l) => l !== layerName && !allowedDeps.includes(l));

    if (disallowedLayers.length > 0) {
      const fromPattern = layerPathsToRegex(layerDef.patterns);
      const toPatterns = disallowedLayers
        .map((l) => definition.layers[l]?.patterns ?? [])
        .flat()
        .map((p) => globToRegex(p));

      if (toPatterns.length > 0) {
        rules.push({
          name: `no-${layerName}-to-disallowed`,
          severity: mapSeverity(options.default_severity),
          comment: `${layerName} layer must not depend on: ${disallowedLayers.join(', ')}`,
          from: { path: fromPattern },
          to: { path: toPatterns.join('|') },
        });
      }
    }
  }

  for (const rule of definition.rules) {
    const fromLayer = definition.layers[rule.from];
    const toLayer = definition.layers[rule.to];
    if (!fromLayer || !toLayer) continue;

    if (!rule.allowed) {
      rules.push({
        name: rule.name,
        severity: mapSeverity(rule.severity),
        comment: rule.message,
        from: { path: layerPathsToRegex(fromLayer.patterns) },
        to: { path: layerPathsToRegex(toLayer.patterns) },
      });
    }
  }

  return deduplicateRules(rules);
}

function mapSeverity(severity: string): 'error' | 'warn' | 'info' | 'ignore' {
  switch (severity) {
    case 'error':
      return 'error';
    case 'warn':
    case 'warning':
      return 'warn';
    case 'info':
      return 'info';
    case 'ignore':
      return 'ignore';
    default:
      throw new Error(
        `Unknown architecture rule severity "${severity}". Expected: error, warn, warning, info, ignore.`
      );
  }
}

const REGEX_METACHARACTERS = /[+?()[\]{}|^$\\]/g;

function globToRegex(glob: string): string {
  let result = '';
  let i = 0;
  while (i < glob.length) {
    const char = glob[i];
    const nextChar = glob[i + 1];
    const charAfterNext = glob[i + 2];

    if (char === '*' && nextChar === '*') {
      if (charAfterNext === '/') {
        result += '(.*\\/)?';
        i += 3;
      } else {
        result += '.*';
        i += 2;
      }
    } else if (char === '*') {
      result += '[^\\/]*';
      i += 1;
    } else if (char === '.') {
      result += '\\.';
      i += 1;
    } else if (char === '/') {
      result += '\\/';
      i += 1;
    } else if (REGEX_METACHARACTERS.test(char)) {
      result += '\\' + char;
      i += 1;
    } else {
      result += char;
      i += 1;
    }
  }
  return result;
}

function layerPathsToRegex(patterns: string[]): string {
  return patterns.map((p) => globToRegex(p) + '$').join('|');
}
