//! INTD-001 (proto half): wire types shared by the Anvil intercept
//! daemon, launcher, and future drivers.
//!
//! Scope kept deliberately narrow: identifiers, the IPC command enum,
//! the NDJSON envelope, and (with INTD-003) the `SessionRecord` /
//! `SessionStatus` shapes that the registry serialises onto the wire.
//! Fence shapes and full enforcement-decision payloads still arrive
//! with INTD-005 and INTD-007 respectively — landing them here
//! pre-empts design choices that should fall out of those tasks.
//!
//! See `plans/modules/intercept-daemon.aps.md` and
//! `plans/decisions/015-intercept-loop-enforcement.md`.

#![forbid(unsafe_code)]

pub mod enforcement_config;
pub mod protocol;
pub mod session;
pub mod status;

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Stable identifier for an intercept session.
///
/// Generated by the launcher when a new agent process is registered;
/// opaque to the daemon. Wire format is a string so future ID schemes
/// (UUID v7, ULID, etc.) can land without a proto break.
///
/// Validation policy: this layer accepts any string, including the
/// empty string. The daemon (INTD-003 session registry) is the single
/// authority on uniqueness and well-formedness; rejecting bad ids at
/// this layer would couple the wire format to the registry's policy
/// and make protocol evolution painful.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SessionId(pub String);

impl SessionId {
    /// Construct a session id from any string-like value. No validation:
    /// the daemon is the single authority on uniqueness.
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// Borrow the underlying string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// IPC commands the launcher and drivers send to the daemon over
/// NDJSON. The minimal A1 set; additional variants will land with
/// INTD-002 (IPC listener) and INTD-003 (session registry).
///
/// Tagged externally as `{ "command": "register-session", ... }` so
/// future variants can carry arbitrary payloads without ambiguity.
/// Unknown command names are rejected at deserialise time — see the
/// `unknown_command_variant_fails_to_deserialise` test for the
/// contract pin INTD-002 reads against.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "command", rename_all = "kebab-case")]
pub enum IpcCommand {
    /// Register a new session with the daemon. The worktree path is
    /// the authority key the registry canonicalises before use. PID
    /// / PGID arrive later via a follow-up update command.
    ///
    /// MLP2-023: `agent_tag` is optional. When omitted (the wire
    /// shape pre-MLP2-023 daemons emit), the registry enforces the
    /// historical "one session per worktree" constraint. When
    /// supplied, multiple sessions with distinct tags can co-exist
    /// on the same canonical worktree — the daemon's per-task fence
    /// keying (MLP2-026) distinguishes them.
    ///
    /// Backward-compat: `#[serde(default, skip_serializing_if)]`
    /// means a pre-MLP2-023 envelope (no `agent_tag` key)
    /// deserialises as `None`; a new envelope with `Some` is parsed
    /// by older daemons that tolerate unknown fields (none of the
    /// in-tree daemons use `deny_unknown_fields` on this variant —
    /// pinned by
    /// `register_session_without_agent_tag_round_trips` and
    /// `register_session_with_agent_tag_round_trips`).
    RegisterSession {
        session_id: SessionId,
        worktree: PathBuf,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        agent_tag: Option<session::AgentTag>,
        /// MLP2-025b: launcher PID + `pid_starttime` for the
        /// lineage anchor. The two are paired in one struct
        /// (`LineageAnchor`) so the "one supplied, other not"
        /// mis-pairing is foreclosed by the type. When `Some`,
        /// the daemon seeds the `(pid, pid_starttime)` lineage
        /// index for the spoof cross-check (MLP2-025).
        ///
        /// Backward-compat: pre-MLP2-025b launchers omit the
        /// field; the daemon takes the legacy register path and
        /// the session does not get a lineage anchor (any
        /// env-tag from a child of the launcher will classify as
        /// `Cross::Spoofed` — the safe default). Pinned by
        /// `register_session_without_lineage_round_trips` and
        /// `register_session_with_lineage_round_trips`.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        lineage: Option<session::LineageAnchor>,
    },
    /// Heartbeat from a registered session to refresh its liveness TTL
    /// (INTD-003 will enforce a 30 s default).
    Heartbeat { session_id: SessionId },
    /// Unregister a session, releasing it from the registry.
    UnregisterSession { session_id: SessionId },
    /// MLP2-074: post-spawn lineage-anchor narrowing. The launcher
    /// registers itself first (the lineage index points at the
    /// launcher's `(pid, pid_starttime)`); after spawning the agent
    /// child it calls this command to swing the anchor onto the
    /// child's `(pid, pid_starttime)`. The daemon authenticates the
    /// caller as the registering launcher via peer credentials before
    /// updating the registry, so a same-UID neighbour cannot reattach
    /// someone else's session to its own descendants.
    ///
    /// Wire shape:
    /// `{"command": "report-process", "session_id": "...", "pid": N, "pid_starttime": N}`.
    /// Pre-MLP2-074 daemons reject with `Method not found` and the
    /// launcher absorbs the failure
    /// (`crates/anvil-run/src/spawn.rs::report_to_daemon`); new daemons
    /// accept it. Pinned by `report_process_round_trips` and
    /// `report_process_uses_kebab_case_discriminator`.
    ReportProcess {
        session_id: SessionId,
        pid: u32,
        pid_starttime: u64,
    },
    /// List all currently registered sessions. Diagnostic / status
    /// query — used by `anvil intercept status` (INTD-011) and the
    /// launcher's reconciliation flow.
    ListSessions,
    /// Query the daemon's full status snapshot — sessions, worktrees,
    /// fences, health, and latency rollups. INTD-011. The wire-level
    /// JSON-RPC method name is `query_status` (resolved by the IPC
    /// layer); this enum variant is the in-memory dispatch shape.
    QueryStatus,
    /// MLP2-026: clear a worktree's `degraded:fence-cascade`
    /// engaged state and reset its in-memory rate window. The
    /// daemon overwrites any client-supplied `operator` field
    /// with values it derives from the peer credentials of the
    /// connection itself — clients SHOULD send `operator: None`
    /// or omit the field. The audit-of-record is the daemon-
    /// derived [`session::OperatorContext`]; the
    /// `--acknowledge-cascade` CLI flag is UX intent only.
    ///
    /// Wire shape: `{"command": "unblock-cascade", "worktree": "...", "operator": ...?}`.
    /// See `plans/specs/2026-05-16-mlp2-026-fence-cascade-control-lane.md`
    /// §3.4.
    UnblockCascade {
        worktree: PathBuf,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        operator: Option<session::OperatorContext>,
    },
    /// RCLI3-017b: clear a single fenced worktree from the daemon's
    /// in-memory state and disk persistence. Wraps the
    /// `FenceStore::unblock_worktree` primitive INTD-007 introduced.
    /// Cascade state (MLP2-026) is a distinct concern — clearing
    /// per-fence records does NOT clear `degraded:fence-cascade`,
    /// and vice versa.
    ///
    /// Wire shape: `{"command": "unblock-worktree", "worktree": "..."}`.
    /// Response: `{"ok": bool}` — `true` when a fence was removed,
    /// `false` for the idempotent no-op case (no fence was engaged).
    UnblockWorktree { worktree: PathBuf },
    /// MLP2-071 (INTD-015 wire-up): flip this connection into
    /// telemetry-subscriber mode. The daemon mints the `SubscriberId`
    /// from the connection's peer credentials at accept time — the
    /// wire frame carries NO identity claim, mirroring the defence
    /// `originating_driver_id` already relies on.
    ///
    /// After the daemon acknowledges the frame, every
    /// `anvil.notification.v1` envelope the producer broadcasts is
    /// routed through `Fanout::route` for this subscriber; the
    /// resulting `Delivery::Allow` or `Delivery::Redact(envelope)`
    /// is written back to the same NDJSON socket as a notification
    /// (`id: None`). `Delivery::Deny` produces no on-wire frame —
    /// the subscriber sees nothing for events it is not authorised
    /// to receive.
    ///
    /// Subsequent control-lane commands on the same connection
    /// remain dispatchable; the IPC layer multiplexes outbound
    /// telemetry frames against inbound command frames.
    ///
    /// Backward-compat: pre-MLP2-071 daemons reject this command at
    /// the JSON-RPC dispatch layer with the standard
    /// `Method not found` error; new daemons accept it. Pinned by
    /// `subscribe_telemetry_round_trips` and
    /// `subscribe_telemetry_uses_kebab_case_discriminator`.
    SubscribeTelemetry {
        /// Optional subset filter the subscriber applies *after* the
        /// daemon's own filter. `None` (or an empty filter struct) =
        /// every envelope the fan-out approves. `Some(filter)` lets
        /// a driver narrow further (e.g. only its own session ids)
        /// without changing the daemon's visibility boundary.
        ///
        /// V1 honours `session_ids` if supplied; richer filtering
        /// (priority floor, rule-id allowlist) is forward-compat
        /// follow-up — additional fields land on
        /// `TelemetrySubscriberFilter` with the same
        /// `#[serde(default, skip_serializing_if = "Option::is_none")]`
        /// pattern.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        filter: Option<TelemetrySubscriberFilter>,
    },
    /// MLP2-071: symmetric tear-down for `SubscribeTelemetry`.
    /// Optional — disconnecting the IPC socket also unregisters the
    /// subscriber, so this frame is primarily for clients that want
    /// to stop receiving without dropping the connection.
    ///
    /// Pinned by `unsubscribe_telemetry_round_trips`.
    UnsubscribeTelemetry,
}

/// MLP2-071 (INTD-015 wire-up): optional client-side filter applied
/// on top of the daemon-enforced default-deny filter. The daemon's
/// `Fanout::route` is the load-bearing visibility boundary; this
/// struct lets a subscriber narrow further without changing the
/// daemon's posture.
///
/// All fields are optional so the wire shape grows additively. An
/// empty filter (all-`None` fields) is equivalent to no filter.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TelemetrySubscriberFilter {
    /// When `Some`, only envelopes whose `originating_session_id`
    /// matches one of the listed ids are forwarded. The daemon
    /// still enforces ownership / cross-session policy first —
    /// this filter is strictly a narrowing hint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_ids: Option<Vec<SessionId>>,
}

/// Single NDJSON envelope. One line on the wire = one envelope. The
/// optional `id` carries the JSON-RPC-style request correlation token
/// so daemon responses can be matched back to launcher requests.
///
/// **Wire-level note:** `{"id": null, ...}` deserialises identically
/// to `{...}` (no `id` field): both yield `id: None`. Any code that
/// uses `id.is_some()` to distinguish requests from notifications
/// MUST treat both forms the same — INTD-002's response router
/// cannot rely on serde to surface the difference. Pinned by the
/// `explicit_null_id_deserialises_as_notification` test.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IpcEnvelope {
    /// Optional correlation id. `None` (or wire-level `null`) means a
    /// notification: no response is expected.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The command payload.
    #[serde(flatten)]
    pub command: IpcCommand,
}

impl IpcEnvelope {
    /// Build a notification envelope (no `id`).
    #[must_use]
    pub fn notification(command: IpcCommand) -> Self {
        Self { id: None, command }
    }

    /// Build a request envelope with a correlation id.
    #[must_use]
    pub fn request(id: impl Into<String>, command: IpcCommand) -> Self {
        Self {
            id: Some(id.into()),
            command,
        }
    }
}

/// Wire snapshot of a registry entry. Mirrors the in-memory state the
/// daemon's session registry (INTD-003) keeps for each active session
/// so callers of `list-sessions` and the diagnostic surfaces (INTD-011)
/// see the same shape.
///
/// Timestamps are pinned as `u64` Unix seconds rather than `Instant`
/// so the format is stable across a daemon restart and serialisable —
/// `Instant` is process-local and not `Serialize`. The registry
/// converts to/from `Instant` internally when it needs to compare
/// against a TTL.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionRecord {
    pub id: SessionId,
    pub worktree: std::path::PathBuf,
    pub pid: Option<u32>,
    /// Unix process group id; populated by the daemon once the launcher
    /// has reported it. None on Windows; the Job Object handle is
    /// tracked out-of-band by INTD-006.
    pub pgid: Option<i32>,
    /// Start time as Unix seconds since epoch, set by the registry on
    /// register; never updated. Helps PID-reuse defence in INTD-006.
    pub started_at_unix: u64,
    /// Most recent heartbeat as Unix seconds since epoch; refreshed by
    /// `heartbeat`. Compared against the TTL by `evict_stale`.
    pub last_heartbeat_unix: u64,
    pub status: SessionStatus,
    /// MLP2-023: composite identity of the agent owning this session,
    /// when one was supplied at registration. `None` for legacy single-
    /// agent worktrees (the daemon's existing "one session per
    /// worktree" path). When `Some(tag)` is set, multiple sessions can
    /// co-exist on the same canonical worktree provided their tags
    /// differ — that is what makes per-task fence isolation possible.
    ///
    /// Backward-compatible on the wire via `skip_serializing_if`: a
    /// pre-MLP2-023 daemon emitting a record without the field
    /// continues to deserialise here as `None`; a new daemon emitting
    /// a record with `Some` is parsed correctly by older clients that
    /// haven't declared the field as long as they tolerate unknown
    /// keys (none of the in-tree consumers use `deny_unknown_fields`
    /// on this struct — pinned by the
    /// `session_record_round_trips_without_agent_tag_field` and
    /// `session_record_with_agent_tag_is_optional_on_the_wire` tests).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_tag: Option<session::AgentTag>,
    /// MLP2-025: tag the **daemon** issued at registration time,
    /// captured from the registering PID's lineage. Mirrors the
    /// client-supplied [`Self::agent_tag`] but is authoritative for
    /// the spoof cross-check: env-supplied `AgentTag` values are
    /// honoured only when they match a `daemon_issued_tag` on the
    /// writer's PID lineage.
    ///
    /// Wire-additive via `skip_serializing_if` (same convention as
    /// `agent_tag`). Pinned by the `daemon_issued_tag_wire_compat`,
    /// `session_record_with_daemon_issued_tag_round_trips`, and
    /// `daemon_issued_tag_omitted_when_none` tests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub daemon_issued_tag: Option<session::AgentTag>,
}

/// Liveness state of a `SessionRecord`. The registry snapshot only
/// contains `Active` records — stale sessions are evicted by removing
/// their entries outright, not by flipping to `Ended`. `Ended` is
/// reserved for downstream notification / reporting surfaces (INTD-013
/// telemetry mirror) where the eviction event itself is the payload;
/// `list-sessions` registry results never include `Ended` records.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SessionStatus {
    Active,
    Ended,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_id_round_trips_string() {
        let id = SessionId::new("sess_abc123");
        assert_eq!(id.as_str(), "sess_abc123");
    }

    /// Documents the proto-layer policy: empty session ids are
    /// accepted at this layer. Validation belongs to INTD-003.
    /// Changing this behaviour requires updating both the doc on
    /// `SessionId` and the registry's input policy.
    #[test]
    fn session_id_accepts_empty_string_validation_is_intd_003_responsibility() {
        let id = SessionId::new("");
        assert_eq!(id.as_str(), "");
    }

    #[test]
    fn register_session_envelope_serialises_to_ndjson_shape() {
        let envelope = IpcEnvelope::request(
            "req-1",
            IpcCommand::RegisterSession {
                session_id: SessionId::new("sess_abc"),
                worktree: PathBuf::from("/tmp/wt"),
                agent_tag: None,
                lineage: None,
            },
        );

        let line = serde_json::to_string(&envelope).expect("serialise");
        let parsed: serde_json::Value = serde_json::from_str(&line).expect("parse back");
        assert_eq!(parsed["id"], "req-1");
        assert_eq!(parsed["command"], "register-session");
        assert_eq!(parsed["session_id"], "sess_abc");
        assert_eq!(parsed["worktree"], "/tmp/wt");
        assert!(
            parsed.get("agent_tag").is_none(),
            "agent_tag absent from envelope when None: got {line}"
        );
        assert!(
            parsed.get("lineage").is_none(),
            "lineage absent from envelope when None: got {line}"
        );
    }

    /// MLP2-023 wire-compat: a pre-MLP2-023 envelope (no `agent_tag`
    /// key) deserialises with the field defaulted to `None`.
    #[test]
    fn register_session_without_agent_tag_round_trips() {
        let wire = r#"{"id":"req-1","command":"register-session","session_id":"sess_abc","worktree":"/tmp/wt"}"#;
        let envelope: IpcEnvelope = serde_json::from_str(wire).expect("deserialise legacy");
        match envelope.command {
            IpcCommand::RegisterSession {
                session_id,
                worktree,
                agent_tag,
                lineage,
            } => {
                assert_eq!(session_id, SessionId::new("sess_abc"));
                assert_eq!(worktree, PathBuf::from("/tmp/wt"));
                assert!(
                    agent_tag.is_none(),
                    "missing agent_tag field defaults to None"
                );
                assert!(lineage.is_none(), "missing lineage field defaults to None");
            }
            other => panic!("expected RegisterSession, got {other:?}"),
        }
    }

    /// MLP2-023: a new envelope carrying an `agent_tag` parses
    /// correctly and survives a round-trip without dropping the
    /// composite identity.
    #[test]
    fn register_session_with_agent_tag_round_trips() {
        let envelope = IpcEnvelope::request(
            "req-2",
            IpcCommand::RegisterSession {
                session_id: SessionId::new("sess_abc"),
                worktree: PathBuf::from("/tmp/wt"),
                agent_tag: Some(session::AgentTag::new(
                    "anvil-run",
                    "claude-code-1",
                    1_700_000_042,
                )),
                lineage: None,
            },
        );

        let line = serde_json::to_string(&envelope).expect("serialise");
        let parsed: serde_json::Value = serde_json::from_str(&line).expect("parse back");
        assert_eq!(parsed["agent_tag"]["driver_id"], "anvil-run");
        assert_eq!(parsed["agent_tag"]["claimed_agent_id"], "claude-code-1");
        assert_eq!(parsed["agent_tag"]["pid_starttime"], 1_700_000_042);

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope, "agent_tag round-trips losslessly");
    }

    /// MLP2-025b wire-compat: a pre-MLP2-025b envelope (no `lineage`
    /// key) deserialises with the field defaulted to `None`.
    #[test]
    fn register_session_without_lineage_round_trips() {
        let wire = r#"{"id":"req-3","command":"register-session","session_id":"sess_l","worktree":"/tmp/wt"}"#;
        let envelope: IpcEnvelope = serde_json::from_str(wire).expect("deserialise legacy");
        match envelope.command {
            IpcCommand::RegisterSession { lineage, .. } => {
                assert!(lineage.is_none(), "missing lineage field defaults to None");
            }
            other => panic!("expected RegisterSession, got {other:?}"),
        }
    }

    /// MLP2-025b: a new envelope carrying `lineage` parses correctly
    /// and survives a round-trip. The launcher reports its own
    /// `pid` + `pid_starttime`; the daemon trusts this register-time
    /// claim.
    #[test]
    fn register_session_with_lineage_round_trips() {
        let envelope = IpcEnvelope::request(
            "req-4",
            IpcCommand::RegisterSession {
                session_id: SessionId::new("sess_anchored"),
                worktree: PathBuf::from("/tmp/wt"),
                agent_tag: None,
                lineage: Some(session::LineageAnchor {
                    pid: 4242,
                    pid_starttime: 1_700_000_500,
                }),
            },
        );

        let line = serde_json::to_string(&envelope).expect("serialise");
        let parsed: serde_json::Value = serde_json::from_str(&line).expect("parse back");
        assert_eq!(parsed["lineage"]["pid"], 4242);
        assert_eq!(parsed["lineage"]["pid_starttime"], 1_700_000_500);

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope, "lineage round-trips losslessly");
    }

    /// MLP2-025b: `lineage` is omitted from the wire when `None`,
    /// mirroring the `agent_tag` precedent. Confirms the
    /// `#[serde(default, skip_serializing_if = "Option::is_none")]`
    /// guard on the new field.
    #[test]
    fn register_session_omits_lineage_when_none() {
        let envelope = IpcEnvelope::request(
            "req-5",
            IpcCommand::RegisterSession {
                session_id: SessionId::new("sess_n"),
                worktree: PathBuf::from("/tmp/wt"),
                agent_tag: None,
                lineage: None,
            },
        );
        let line = serde_json::to_string(&envelope).expect("serialise");
        assert!(
            !line.contains("\"lineage\""),
            "lineage must be omitted on wire when None: {line}"
        );
    }

    /// MLP2-074: `ReportProcess` round-trips with the kebab-case
    /// `report-process` discriminator, carrying the launcher-supplied
    /// child `(pid, pid_starttime)` for the daemon's lineage-anchor
    /// narrowing.
    #[test]
    fn report_process_round_trips() {
        let envelope = IpcEnvelope::request(
            "req-rp",
            IpcCommand::ReportProcess {
                session_id: SessionId::new("sess_rp"),
                pid: 4242,
                pid_starttime: 1_700_000_000,
            },
        );
        let line = serde_json::to_string(&envelope).expect("serialise");
        assert!(line.contains("\"report-process\""), "kebab-case: {line}");
        assert!(line.contains("\"pid\":4242"), "pid present: {line}");
        assert!(
            line.contains("\"pid_starttime\":1700000000"),
            "pid_starttime present: {line}",
        );

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope, "report-process round-trips losslessly");
    }

    /// MLP2-074: the discriminator string follows the same kebab-case
    /// convention as every other variant — pinned alongside the
    /// generic discriminator check below so renames stay visible.
    #[test]
    fn report_process_uses_kebab_case_discriminator() {
        let serialised = serde_json::to_string(&IpcCommand::ReportProcess {
            session_id: SessionId::new("x"),
            pid: 1,
            pid_starttime: 1,
        })
        .expect("serialise");
        assert!(
            serialised.contains("\"report-process\""),
            "got: {serialised}"
        );
    }

    #[test]
    fn heartbeat_notification_omits_id_field() {
        let envelope = IpcEnvelope::notification(IpcCommand::Heartbeat {
            session_id: SessionId::new("sess_abc"),
        });

        let line = serde_json::to_string(&envelope).expect("serialise");
        assert!(
            !line.contains("\"id\""),
            "notifications must not include an id field, got: {line}",
        );
    }

    #[test]
    fn list_sessions_round_trips() {
        let envelope = IpcEnvelope::request("req-list", IpcCommand::ListSessions);
        let line = serde_json::to_string(&envelope).expect("serialise");
        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope);
    }

    #[test]
    fn ipc_command_uses_kebab_case_discriminator() {
        let unreg = serde_json::to_string(&IpcCommand::UnregisterSession {
            session_id: SessionId::new("x"),
        })
        .expect("serialise");
        assert!(unreg.contains("\"unregister-session\""), "got: {unreg}");
    }

    /// MLP2-026: `UnblockCascade` round-trips through the wire with
    /// kebab-case discriminator `unblock-cascade`. `operator` is
    /// omitted when None (skip-if-none).
    #[test]
    fn unblock_cascade_round_trips_through_wire() {
        let envelope = IpcEnvelope::request(
            "req-uc",
            IpcCommand::UnblockCascade {
                worktree: PathBuf::from("/work/wt"),
                operator: None,
            },
        );
        let line = serde_json::to_string(&envelope).expect("serialise");
        assert!(line.contains("\"unblock-cascade\""), "kebab-case: {line}");
        assert!(line.contains("\"/work/wt\""), "worktree present: {line}");
        assert!(
            !line.contains("\"operator\""),
            "operator omitted when None: {line}"
        );

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope);
    }

    /// RCLI3-017b: `UnblockWorktree` round-trips through the wire
    /// with the kebab-case discriminator `unblock-worktree`. The
    /// variant carries only the `worktree` field — no per-fence
    /// audit-context analogue to the cascade's `operator` (cascade
    /// audit-of-record is daemon-derived; per-fence relies on the
    /// existing fence-record fields).
    #[test]
    fn unblock_worktree_round_trips_through_wire() {
        let envelope = IpcEnvelope::request(
            "req-uw",
            IpcCommand::UnblockWorktree {
                worktree: PathBuf::from("/work/wt"),
            },
        );
        let line = serde_json::to_string(&envelope).expect("serialise");
        assert!(line.contains("\"unblock-worktree\""), "kebab-case: {line}");
        assert!(line.contains("\"/work/wt\""), "worktree present: {line}");

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope);
    }

    /// MLP2-026: `OperatorContext` round-trips with all fields
    /// populated. Spec §3.3 wire shape.
    #[test]
    fn operator_context_round_trips_fully_populated() {
        let envelope = IpcEnvelope::request(
            "req-op",
            IpcCommand::UnblockCascade {
                worktree: PathBuf::from("/work/wt"),
                operator: Some(session::OperatorContext {
                    uid: Some(1000),
                    pid: Some(4242),
                    hostname: Some("test-host".to_string()),
                }),
            },
        );
        let line = serde_json::to_string(&envelope).expect("serialise");
        let parsed: serde_json::Value = serde_json::from_str(&line).expect("parse");
        assert_eq!(parsed["operator"]["uid"], 1000);
        assert_eq!(parsed["operator"]["pid"], 4242);
        assert_eq!(parsed["operator"]["hostname"], "test-host");

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope);
    }

    /// Pinned contract for INTD-002's response router: an explicit
    /// `null` id is indistinguishable from an absent id at this
    /// layer. Both are notifications.
    #[test]
    fn explicit_null_id_deserialises_as_notification() {
        let wire = r#"{"id": null, "command": "list-sessions"}"#;
        let envelope: IpcEnvelope = serde_json::from_str(wire).expect("deserialise null id");
        assert_eq!(
            envelope.id, None,
            "explicit null id deserialises as None — same as a notification",
        );

        // The reverse direction: a request envelope serialises with
        // `id` present; a notification omits it. Confirms the
        // round-trip cannot smuggle a null past the boundary.
        let line = serde_json::to_string(&envelope).expect("serialise back");
        assert!(
            !line.contains("\"id\""),
            "round-trip must not reintroduce a null id: {line}",
        );
    }

    /// `SessionRecord` round-trips through JSON without losing any
    /// field, and `SessionStatus` keeps the kebab-case wire form
    /// pinned by `IpcCommand`'s convention.
    #[test]
    fn session_record_round_trips_through_json() {
        let record = SessionRecord {
            id: SessionId::new("sess_abc"),
            worktree: std::path::PathBuf::from("/tmp/wt"),
            pid: Some(4242),
            pgid: Some(4242),
            started_at_unix: 1_700_000_000,
            last_heartbeat_unix: 1_700_000_010,
            status: SessionStatus::Active,
            agent_tag: None,
            daemon_issued_tag: None,
        };

        let line = serde_json::to_string(&record).expect("serialise");
        assert!(line.contains("\"active\""), "kebab-case status: {line}");
        assert!(
            !line.contains("agent_tag"),
            "agent_tag absent on wire when None: {line}"
        );

        let back: SessionRecord = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, record);
    }

    /// MLP2-023 wire-compat: a pre-MLP2-023 `SessionRecord`
    /// serialisation (no `agent_tag` key) deserialises with the field
    /// defaulted to `None`. This keeps the daemon ↔ launcher
    /// contract additive-only.
    #[test]
    fn session_record_round_trips_without_agent_tag_field() {
        let wire = r#"{
            "id":"sess_abc",
            "worktree":"/tmp/wt",
            "pid":null,
            "pgid":null,
            "started_at_unix":1700000000,
            "last_heartbeat_unix":1700000010,
            "status":"active"
        }"#;
        let record: SessionRecord = serde_json::from_str(wire).expect("legacy deserialise");
        assert!(record.agent_tag.is_none(), "missing field defaults to None");
        assert_eq!(record.id, SessionId::new("sess_abc"));
    }

    /// MLP2-023: a `SessionRecord` carrying an `agent_tag` round-
    /// trips losslessly and surfaces the composite identity to
    /// consumers.
    #[test]
    fn session_record_with_agent_tag_is_optional_on_the_wire() {
        let record = SessionRecord {
            id: SessionId::new("sess_tagged"),
            worktree: std::path::PathBuf::from("/tmp/wt"),
            pid: None,
            pgid: None,
            started_at_unix: 1_700_000_000,
            last_heartbeat_unix: 1_700_000_010,
            status: SessionStatus::Active,
            agent_tag: Some(session::AgentTag::new(
                "anvil-run",
                "claude-code-2",
                1_700_000_042,
            )),
            daemon_issued_tag: None,
        };
        let line = serde_json::to_string(&record).expect("serialise");
        assert!(
            line.contains("\"agent_tag\""),
            "agent_tag present on wire when Some: {line}"
        );
        let back: SessionRecord = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, record);
    }

    /// MLP2-025: a `SessionRecord` without `daemon_issued_tag` still
    /// deserialises losslessly; the field defaults to `None`. Pins the
    /// wire-additive contract: pre-MLP2-025 daemons emitting a record
    /// without the new field continue to round-trip via newer readers.
    #[test]
    fn daemon_issued_tag_wire_compat() {
        let wire = r#"{
            "id":"sess_abc",
            "worktree":"/tmp/wt",
            "pid":null,
            "pgid":null,
            "started_at_unix":1700000000,
            "last_heartbeat_unix":1700000010,
            "status":"active"
        }"#;
        let record: SessionRecord = serde_json::from_str(wire).expect("legacy deserialise");
        assert!(
            record.daemon_issued_tag.is_none(),
            "missing daemon_issued_tag field defaults to None"
        );
    }

    /// MLP2-025: a `SessionRecord` carrying both `agent_tag` (client-
    /// supplied) and `daemon_issued_tag` (daemon mirror) round-trips
    /// losslessly. The two fields are independent — the daemon may
    /// issue a tag at registration even when the client didn't supply
    /// one, and vice versa, though typical usage has them paired.
    #[test]
    fn session_record_with_daemon_issued_tag_round_trips() {
        let record = SessionRecord {
            id: SessionId::new("sess_tagged"),
            worktree: std::path::PathBuf::from("/tmp/wt"),
            pid: None,
            pgid: None,
            started_at_unix: 1_700_000_000,
            last_heartbeat_unix: 1_700_000_010,
            status: SessionStatus::Active,
            agent_tag: Some(session::AgentTag::new(
                "anvil-run",
                "claude-code-2",
                1_700_000_042,
            )),
            daemon_issued_tag: Some(session::AgentTag::new(
                "anvil-run",
                "claude-code-2",
                1_700_000_042,
            )),
        };
        let line = serde_json::to_string(&record).expect("serialise");
        assert!(
            line.contains("\"daemon_issued_tag\""),
            "daemon_issued_tag present on wire when Some: {line}"
        );
        let back: SessionRecord = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, record);
    }

    /// MLP2-025: `daemon_issued_tag` is omitted from the wire when
    /// `None`, mirroring the `agent_tag` precedent. Confirms the
    /// `#[serde(skip_serializing_if = "Option::is_none")]` guard.
    #[test]
    fn daemon_issued_tag_omitted_when_none() {
        let record = SessionRecord {
            id: SessionId::new("sess_no_daemon_tag"),
            worktree: std::path::PathBuf::from("/tmp/wt"),
            pid: None,
            pgid: None,
            started_at_unix: 1_700_000_000,
            last_heartbeat_unix: 1_700_000_010,
            status: SessionStatus::Active,
            agent_tag: None,
            daemon_issued_tag: None,
        };
        let line = serde_json::to_string(&record).expect("serialise");
        assert!(
            !line.contains("daemon_issued_tag"),
            "daemon_issued_tag must be omitted on wire when None: {line}"
        );
    }

    #[test]
    fn session_status_serialises_as_kebab_case() {
        let active = serde_json::to_string(&SessionStatus::Active).expect("serialise");
        assert_eq!(active, "\"active\"");
        let ended = serde_json::to_string(&SessionStatus::Ended).expect("serialise");
        assert_eq!(ended, "\"ended\"");
    }

    /// MLP2-071 (INTD-015 wire-up): `SubscribeTelemetry` round-trips
    /// through the wire with the kebab-case discriminator
    /// `subscribe-telemetry`. The `filter` field is omitted when
    /// `None` (skip-if-none guard), matching the `operator` /
    /// `agent_tag` / `lineage` precedents.
    #[test]
    fn subscribe_telemetry_round_trips() {
        let envelope =
            IpcEnvelope::request("req-sub", IpcCommand::SubscribeTelemetry { filter: None });
        let line = serde_json::to_string(&envelope).expect("serialise");
        assert!(
            line.contains("\"subscribe-telemetry\""),
            "kebab-case discriminator: {line}"
        );
        assert!(
            !line.contains("\"filter\""),
            "filter omitted when None: {line}"
        );

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope);
    }

    /// MLP2-071: the kebab-case discriminator pin is the contract
    /// pre-MLP2-071 daemons need to reject; pinning it explicitly
    /// keeps the rename-rule guard from drifting.
    #[test]
    fn subscribe_telemetry_uses_kebab_case_discriminator() {
        let sub = serde_json::to_string(&IpcCommand::SubscribeTelemetry { filter: None })
            .expect("serialise");
        assert!(
            sub.contains("\"subscribe-telemetry\""),
            "subscribe-telemetry: got {sub}"
        );
        let unsub = serde_json::to_string(&IpcCommand::UnsubscribeTelemetry).expect("serialise");
        assert!(
            unsub.contains("\"unsubscribe-telemetry\""),
            "unsubscribe-telemetry: got {unsub}"
        );
    }

    /// MLP2-071: a populated `TelemetrySubscriberFilter` round-trips
    /// with `session_ids` carried as an array on the wire.
    #[test]
    fn subscribe_telemetry_with_session_filter_round_trips() {
        let envelope = IpcEnvelope::request(
            "req-sub-filter",
            IpcCommand::SubscribeTelemetry {
                filter: Some(TelemetrySubscriberFilter {
                    session_ids: Some(vec![SessionId::new("sess_a"), SessionId::new("sess_b")]),
                }),
            },
        );
        let line = serde_json::to_string(&envelope).expect("serialise");
        let parsed: serde_json::Value = serde_json::from_str(&line).expect("parse");
        assert_eq!(parsed["filter"]["session_ids"][0], "sess_a");
        assert_eq!(parsed["filter"]["session_ids"][1], "sess_b");

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope);
    }

    /// MLP2-071: `UnsubscribeTelemetry` round-trips with no payload.
    #[test]
    fn unsubscribe_telemetry_round_trips() {
        let envelope = IpcEnvelope::request("req-unsub", IpcCommand::UnsubscribeTelemetry);
        let line = serde_json::to_string(&envelope).expect("serialise");
        assert!(
            line.contains("\"unsubscribe-telemetry\""),
            "kebab-case: {line}"
        );
        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope);
    }

    /// MLP2-071: an empty filter struct (`{}`) deserialises as
    /// `Some(TelemetrySubscriberFilter { session_ids: None })`,
    /// distinct from the omitted-filter case which deserialises as
    /// `filter: None`. Both shapes are semantically equivalent (no
    /// further narrowing) and must round-trip cleanly.
    #[test]
    fn subscribe_telemetry_empty_filter_object_deserialises() {
        let wire = r#"{"id": "req-empty", "command": "subscribe-telemetry", "filter": {}}"#;
        let envelope: IpcEnvelope = serde_json::from_str(wire).expect("deserialise");
        match envelope.command {
            IpcCommand::SubscribeTelemetry { filter } => {
                assert_eq!(
                    filter,
                    Some(TelemetrySubscriberFilter { session_ids: None }),
                    "empty filter object parses as Some(default) — semantically same as None"
                );
            }
            other => panic!("expected SubscribeTelemetry, got {other:?}"),
        }
    }

    /// Pinned contract for INTD-002's NDJSON socket reader: unknown
    /// command names are rejected at deserialise time. The reader's
    /// error-handling path can then choose to skip the line, send a
    /// structured error response, or close the connection — but not
    /// silently dispatch to a default variant.
    #[test]
    fn unknown_command_variant_fails_to_deserialise() {
        let wire = r#"{"command": "future-unknown", "session_id": "x"}"#;
        let result: Result<IpcEnvelope, _> = serde_json::from_str(wire);
        assert!(
            result.is_err(),
            "unknown command names must reject at the proto layer; got Ok({:?})",
            result.ok(),
        );
    }
}
