//! INTD-001 (proto half): wire types shared by the Anvil intercept
//! daemon, launcher, and future drivers.
//!
//! Scope kept deliberately narrow: identifiers, the IPC command enum,
//! the NDJSON envelope, and (with INTD-003) the `SessionRecord` /
//! `SessionStatus` shapes that the registry serialises onto the wire.
//! Fence shapes and full enforcement-decision payloads still arrive
//! with INTD-005 and INTD-007 respectively — landing them here
//! pre-empts design choices that should fall out of those tasks.
//!
//! See `plans/modules/intercept-daemon.aps.md` and
//! `plans/decisions/015-intercept-loop-enforcement.md`.

#![forbid(unsafe_code)]

pub mod enforcement_config;
pub mod protocol;
pub mod session;
pub mod status;

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Stable identifier for an intercept session.
///
/// Generated by the launcher when a new agent process is registered;
/// opaque to the daemon. Wire format is a string so future ID schemes
/// (UUID v7, ULID, etc.) can land without a proto break.
///
/// Validation policy: this layer accepts any string, including the
/// empty string. The daemon (INTD-003 session registry) is the single
/// authority on uniqueness and well-formedness; rejecting bad ids at
/// this layer would couple the wire format to the registry's policy
/// and make protocol evolution painful.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SessionId(pub String);

impl SessionId {
    /// Construct a session id from any string-like value. No validation:
    /// the daemon is the single authority on uniqueness.
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// Borrow the underlying string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// IPC commands the launcher and drivers send to the daemon over
/// NDJSON. The minimal A1 set; additional variants will land with
/// INTD-002 (IPC listener) and INTD-003 (session registry).
///
/// Tagged externally as `{ "command": "register-session", ... }` so
/// future variants can carry arbitrary payloads without ambiguity.
/// Unknown command names are rejected at deserialise time — see the
/// `unknown_command_variant_fails_to_deserialise` test for the
/// contract pin INTD-002 reads against.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "command", rename_all = "kebab-case")]
pub enum IpcCommand {
    /// Register a new session with the daemon. The worktree path is
    /// the authority key the registry canonicalises before use. PID
    /// / PGID arrive later via a follow-up update command.
    ///
    /// MLP2-023: `agent_tag` is optional. When omitted (the wire
    /// shape pre-MLP2-023 daemons emit), the registry enforces the
    /// historical "one session per worktree" constraint. When
    /// supplied, multiple sessions with distinct tags can co-exist
    /// on the same canonical worktree — the daemon's per-task fence
    /// keying (MLP2-026) distinguishes them.
    ///
    /// Backward-compat: `#[serde(default, skip_serializing_if)]`
    /// means a pre-MLP2-023 envelope (no `agent_tag` key)
    /// deserialises as `None`; a new envelope with `Some` is parsed
    /// by older daemons that tolerate unknown fields (none of the
    /// in-tree daemons use `deny_unknown_fields` on this variant —
    /// pinned by
    /// `register_session_without_agent_tag_round_trips` and
    /// `register_session_with_agent_tag_round_trips`).
    RegisterSession {
        session_id: SessionId,
        worktree: PathBuf,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        agent_tag: Option<session::AgentTag>,
    },
    /// Heartbeat from a registered session to refresh its liveness TTL
    /// (INTD-003 will enforce a 30 s default).
    Heartbeat { session_id: SessionId },
    /// Unregister a session, releasing it from the registry.
    UnregisterSession { session_id: SessionId },
    /// List all currently registered sessions. Diagnostic / status
    /// query — used by `anvil intercept status` (INTD-011) and the
    /// launcher's reconciliation flow.
    ListSessions,
    /// Query the daemon's full status snapshot — sessions, worktrees,
    /// fences, health, and latency rollups. INTD-011. The wire-level
    /// JSON-RPC method name is `query_status` (resolved by the IPC
    /// layer); this enum variant is the in-memory dispatch shape.
    QueryStatus,
}

/// Single NDJSON envelope. One line on the wire = one envelope. The
/// optional `id` carries the JSON-RPC-style request correlation token
/// so daemon responses can be matched back to launcher requests.
///
/// **Wire-level note:** `{"id": null, ...}` deserialises identically
/// to `{...}` (no `id` field): both yield `id: None`. Any code that
/// uses `id.is_some()` to distinguish requests from notifications
/// MUST treat both forms the same — INTD-002's response router
/// cannot rely on serde to surface the difference. Pinned by the
/// `explicit_null_id_deserialises_as_notification` test.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IpcEnvelope {
    /// Optional correlation id. `None` (or wire-level `null`) means a
    /// notification: no response is expected.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The command payload.
    #[serde(flatten)]
    pub command: IpcCommand,
}

impl IpcEnvelope {
    /// Build a notification envelope (no `id`).
    #[must_use]
    pub fn notification(command: IpcCommand) -> Self {
        Self { id: None, command }
    }

    /// Build a request envelope with a correlation id.
    #[must_use]
    pub fn request(id: impl Into<String>, command: IpcCommand) -> Self {
        Self {
            id: Some(id.into()),
            command,
        }
    }
}

/// Wire snapshot of a registry entry. Mirrors the in-memory state the
/// daemon's session registry (INTD-003) keeps for each active session
/// so callers of `list-sessions` and the diagnostic surfaces (INTD-011)
/// see the same shape.
///
/// Timestamps are pinned as `u64` Unix seconds rather than `Instant`
/// so the format is stable across a daemon restart and serialisable —
/// `Instant` is process-local and not `Serialize`. The registry
/// converts to/from `Instant` internally when it needs to compare
/// against a TTL.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionRecord {
    pub id: SessionId,
    pub worktree: std::path::PathBuf,
    pub pid: Option<u32>,
    /// Unix process group id; populated by the daemon once the launcher
    /// has reported it. None on Windows; the Job Object handle is
    /// tracked out-of-band by INTD-006.
    pub pgid: Option<i32>,
    /// Start time as Unix seconds since epoch, set by the registry on
    /// register; never updated. Helps PID-reuse defence in INTD-006.
    pub started_at_unix: u64,
    /// Most recent heartbeat as Unix seconds since epoch; refreshed by
    /// `heartbeat`. Compared against the TTL by `evict_stale`.
    pub last_heartbeat_unix: u64,
    pub status: SessionStatus,
    /// MLP2-023: composite identity of the agent owning this session,
    /// when one was supplied at registration. `None` for legacy single-
    /// agent worktrees (the daemon's existing "one session per
    /// worktree" path). When `Some(tag)` is set, multiple sessions can
    /// co-exist on the same canonical worktree provided their tags
    /// differ — that is what makes per-task fence isolation possible.
    ///
    /// Backward-compatible on the wire via `skip_serializing_if`: a
    /// pre-MLP2-023 daemon emitting a record without the field
    /// continues to deserialise here as `None`; a new daemon emitting
    /// a record with `Some` is parsed correctly by older clients that
    /// haven't declared the field as long as they tolerate unknown
    /// keys (none of the in-tree consumers use `deny_unknown_fields`
    /// on this struct — pinned by the
    /// `session_record_round_trips_without_agent_tag_field` and
    /// `session_record_with_agent_tag_is_optional_on_the_wire` tests).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_tag: Option<session::AgentTag>,
}

/// Liveness state of a `SessionRecord`. The registry snapshot only
/// contains `Active` records — stale sessions are evicted by removing
/// their entries outright, not by flipping to `Ended`. `Ended` is
/// reserved for downstream notification / reporting surfaces (INTD-013
/// telemetry mirror) where the eviction event itself is the payload;
/// `list-sessions` registry results never include `Ended` records.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum SessionStatus {
    Active,
    Ended,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_id_round_trips_string() {
        let id = SessionId::new("sess_abc123");
        assert_eq!(id.as_str(), "sess_abc123");
    }

    /// Documents the proto-layer policy: empty session ids are
    /// accepted at this layer. Validation belongs to INTD-003.
    /// Changing this behaviour requires updating both the doc on
    /// `SessionId` and the registry's input policy.
    #[test]
    fn session_id_accepts_empty_string_validation_is_intd_003_responsibility() {
        let id = SessionId::new("");
        assert_eq!(id.as_str(), "");
    }

    #[test]
    fn register_session_envelope_serialises_to_ndjson_shape() {
        let envelope = IpcEnvelope::request(
            "req-1",
            IpcCommand::RegisterSession {
                session_id: SessionId::new("sess_abc"),
                worktree: PathBuf::from("/tmp/wt"),
                agent_tag: None,
            },
        );

        let line = serde_json::to_string(&envelope).expect("serialise");
        let parsed: serde_json::Value = serde_json::from_str(&line).expect("parse back");
        assert_eq!(parsed["id"], "req-1");
        assert_eq!(parsed["command"], "register-session");
        assert_eq!(parsed["session_id"], "sess_abc");
        assert_eq!(parsed["worktree"], "/tmp/wt");
        assert!(
            parsed.get("agent_tag").is_none(),
            "agent_tag absent from envelope when None: got {line}"
        );
    }

    /// MLP2-023 wire-compat: a pre-MLP2-023 envelope (no `agent_tag`
    /// key) deserialises with the field defaulted to `None`.
    #[test]
    fn register_session_without_agent_tag_round_trips() {
        let wire = r#"{"id":"req-1","command":"register-session","session_id":"sess_abc","worktree":"/tmp/wt"}"#;
        let envelope: IpcEnvelope = serde_json::from_str(wire).expect("deserialise legacy");
        match envelope.command {
            IpcCommand::RegisterSession {
                session_id,
                worktree,
                agent_tag,
            } => {
                assert_eq!(session_id, SessionId::new("sess_abc"));
                assert_eq!(worktree, PathBuf::from("/tmp/wt"));
                assert!(
                    agent_tag.is_none(),
                    "missing agent_tag field defaults to None"
                );
            }
            other => panic!("expected RegisterSession, got {other:?}"),
        }
    }

    /// MLP2-023: a new envelope carrying an `agent_tag` parses
    /// correctly and survives a round-trip without dropping the
    /// composite identity.
    #[test]
    fn register_session_with_agent_tag_round_trips() {
        let envelope = IpcEnvelope::request(
            "req-2",
            IpcCommand::RegisterSession {
                session_id: SessionId::new("sess_abc"),
                worktree: PathBuf::from("/tmp/wt"),
                agent_tag: Some(session::AgentTag::new(
                    "anvil-run",
                    "claude-code-1",
                    1_700_000_042,
                )),
            },
        );

        let line = serde_json::to_string(&envelope).expect("serialise");
        let parsed: serde_json::Value = serde_json::from_str(&line).expect("parse back");
        assert_eq!(parsed["agent_tag"]["driver_id"], "anvil-run");
        assert_eq!(parsed["agent_tag"]["claimed_agent_id"], "claude-code-1");
        assert_eq!(parsed["agent_tag"]["pid_starttime"], 1_700_000_042);

        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope, "agent_tag round-trips losslessly");
    }

    #[test]
    fn heartbeat_notification_omits_id_field() {
        let envelope = IpcEnvelope::notification(IpcCommand::Heartbeat {
            session_id: SessionId::new("sess_abc"),
        });

        let line = serde_json::to_string(&envelope).expect("serialise");
        assert!(
            !line.contains("\"id\""),
            "notifications must not include an id field, got: {line}",
        );
    }

    #[test]
    fn list_sessions_round_trips() {
        let envelope = IpcEnvelope::request("req-list", IpcCommand::ListSessions);
        let line = serde_json::to_string(&envelope).expect("serialise");
        let back: IpcEnvelope = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, envelope);
    }

    #[test]
    fn ipc_command_uses_kebab_case_discriminator() {
        let unreg = serde_json::to_string(&IpcCommand::UnregisterSession {
            session_id: SessionId::new("x"),
        })
        .expect("serialise");
        assert!(unreg.contains("\"unregister-session\""), "got: {unreg}");
    }

    /// Pinned contract for INTD-002's response router: an explicit
    /// `null` id is indistinguishable from an absent id at this
    /// layer. Both are notifications.
    #[test]
    fn explicit_null_id_deserialises_as_notification() {
        let wire = r#"{"id": null, "command": "list-sessions"}"#;
        let envelope: IpcEnvelope = serde_json::from_str(wire).expect("deserialise null id");
        assert_eq!(
            envelope.id, None,
            "explicit null id deserialises as None — same as a notification",
        );

        // The reverse direction: a request envelope serialises with
        // `id` present; a notification omits it. Confirms the
        // round-trip cannot smuggle a null past the boundary.
        let line = serde_json::to_string(&envelope).expect("serialise back");
        assert!(
            !line.contains("\"id\""),
            "round-trip must not reintroduce a null id: {line}",
        );
    }

    /// `SessionRecord` round-trips through JSON without losing any
    /// field, and `SessionStatus` keeps the kebab-case wire form
    /// pinned by `IpcCommand`'s convention.
    #[test]
    fn session_record_round_trips_through_json() {
        let record = SessionRecord {
            id: SessionId::new("sess_abc"),
            worktree: std::path::PathBuf::from("/tmp/wt"),
            pid: Some(4242),
            pgid: Some(4242),
            started_at_unix: 1_700_000_000,
            last_heartbeat_unix: 1_700_000_010,
            status: SessionStatus::Active,
            agent_tag: None,
        };

        let line = serde_json::to_string(&record).expect("serialise");
        assert!(line.contains("\"active\""), "kebab-case status: {line}");
        assert!(
            !line.contains("agent_tag"),
            "agent_tag absent on wire when None: {line}"
        );

        let back: SessionRecord = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, record);
    }

    /// MLP2-023 wire-compat: a pre-MLP2-023 `SessionRecord`
    /// serialisation (no `agent_tag` key) deserialises with the field
    /// defaulted to `None`. This keeps the daemon ↔ launcher
    /// contract additive-only.
    #[test]
    fn session_record_round_trips_without_agent_tag_field() {
        let wire = r#"{
            "id":"sess_abc",
            "worktree":"/tmp/wt",
            "pid":null,
            "pgid":null,
            "started_at_unix":1700000000,
            "last_heartbeat_unix":1700000010,
            "status":"active"
        }"#;
        let record: SessionRecord = serde_json::from_str(wire).expect("legacy deserialise");
        assert!(record.agent_tag.is_none(), "missing field defaults to None");
        assert_eq!(record.id, SessionId::new("sess_abc"));
    }

    /// MLP2-023: a `SessionRecord` carrying an `agent_tag` round-
    /// trips losslessly and surfaces the composite identity to
    /// consumers.
    #[test]
    fn session_record_with_agent_tag_is_optional_on_the_wire() {
        let record = SessionRecord {
            id: SessionId::new("sess_tagged"),
            worktree: std::path::PathBuf::from("/tmp/wt"),
            pid: None,
            pgid: None,
            started_at_unix: 1_700_000_000,
            last_heartbeat_unix: 1_700_000_010,
            status: SessionStatus::Active,
            agent_tag: Some(session::AgentTag::new(
                "anvil-run",
                "claude-code-2",
                1_700_000_042,
            )),
        };
        let line = serde_json::to_string(&record).expect("serialise");
        assert!(
            line.contains("\"agent_tag\""),
            "agent_tag present on wire when Some: {line}"
        );
        let back: SessionRecord = serde_json::from_str(&line).expect("deserialise");
        assert_eq!(back, record);
    }

    #[test]
    fn session_status_serialises_as_kebab_case() {
        let active = serde_json::to_string(&SessionStatus::Active).expect("serialise");
        assert_eq!(active, "\"active\"");
        let ended = serde_json::to_string(&SessionStatus::Ended).expect("serialise");
        assert_eq!(ended, "\"ended\"");
    }

    /// Pinned contract for INTD-002's NDJSON socket reader: unknown
    /// command names are rejected at deserialise time. The reader's
    /// error-handling path can then choose to skip the line, send a
    /// structured error response, or close the connection — but not
    /// silently dispatch to a default variant.
    #[test]
    fn unknown_command_variant_fails_to_deserialise() {
        let wire = r#"{"command": "future-unknown", "session_id": "x"}"#;
        let result: Result<IpcEnvelope, _> = serde_json::from_str(wire);
        assert!(
            result.is_err(),
            "unknown command names must reject at the proto layer; got Ok({:?})",
            result.ok(),
        );
    }
}
